### ISSUE TITLE
Timed out after 30000ms caused by small poolSize value

### ISSUE THREAD

**Issue by Cazmon** [AuthMe/AuthMeReloaded#1089]
After 6 - 8 hours of intensive use (9 lobbys on diferents dedi sv i7-OVH) My tps fine 19.99 all time. Any idea?

[17:22:22 INFO]: UUID of player MineSantiJr is 23b3369e-f2d0-37d2-9fa3-df643572f28c
[17:22:22 INFO]: UUID of player LuciiGaymer is c18552a3-3c96-3ea3-a5af-ea7485682357
[17:22:52 WARN]: [AuthMe] Error during SQL operation: [SQLTransientConnectionException]: AuthMeMYSQLPool - Connection is not available, request timed out after 30000ms.
[17:22:52 WARN]: [AuthMe] Error during SQL operation: [SQLTransientConnectionException]: AuthMeMYSQLPool - Connection is not available, request timed out after 30000ms.
[17:22:52 WARN]: [AuthMe] Error during SQL operation: [SQLTransientConnectionException]: AuthMeMYSQLPool - Connection is not available, request timed out after 30000ms.
[17:22:52 INFO]: Deniz[/78.165.58.2:57408] logged in with entity id 5116 at ([hub]33.5, 166.0, -51.5)
[17:22:52 INFO]: com.mojang.authlib.GameProfile@53aeda02[id=6559445a-78d1-358c-8ee3-8cb6a537ed27,name=Elvantito95,properties={textures=[com.mojang.authlib.properties.Property@276531f4]},legacy=false] (/*****:49518) lost connection: Disconnected
[17:22:53 WARN]: [AuthMe] Error during SQL operation: [SQLTransientConnectionException]: AuthMeMYSQLPool - Connection is not available, request timed out after 30000ms.

**Comment by Twonox** [comment]
Your MySQL is shut down at this moment. You use MySQL, don't you ?

**Comment by Cazmon** [comment]
Timmings;
https://timings.spigotmc.org/?url=giwugatuli
Authme Config;
http://pastebin.com/aUiXQU6Y
MYSQL 10.0.28-MariaDB-0+deb8u1
Authme Version; 5.2 Release

**Comment by Twonox** [comment]
Yeah, your mysql should is probably the cause and I also guess that your server shut down,

**Comment by Cazmon** [comment]
This mysql is now for a while in test mode on a dedicated Intel i7-6700K OC 4.7GHz 64 GB DDR4 2400 MHz SSD OVH in the same rack of lobbys servers.

It has always been this mysql alone and running for 2 years very well with authme.

CSF firewall well configured.

A possible problem in the mysql configuration?

My.conf;
Interactive_timeout = 300
Wait_timeout = 300
Maximum number of connections: 400

**Comment by sgdc3** [comment]
@ljacqu Do you have any idea how to debug this issue?

**Comment by ljacqu** [comment]
@Cazmon In AuthMe's config.yml, please locate:

```yml
    # Overrides the size of the DB Connection Pool, -1 = Auto
    poolSize: -1
```

and change the value to maybe 300? Our default is the number of cores on the machine, which I think may be a bad default.

**Comment by sgdc3** [comment]
300? :/ That means 300 threads!

**Comment by sgdc3** [comment]
30 is bwter i think @ljacqu

**Comment by Cazmon** [comment]
@sgdc3 
22 hours with poolSize: 30
No error at the moment. Before that, it was MYSQL errors every 4 hours.
I keep an eye on a few days more and i will write something here. Thanks Authme team.

**Comment by Cazmon** [comment]
Error again when stop the server and when start again the server connection is not available, need reestart the mysql server to work again:

`[19:29:06] [Server thread/INFO]: Stopping the server
[19:29:06] [Server thread/INFO]: Stopping server
[19:29:06] [Server thread/INFO]: [ChestCommands] Disabling ChestCommands v3.1.4
[19:29:06] [Server thread/INFO]: [PlayerPoints] Disabling PlayerPoints v2.1.5-SNAPSHOT
[19:29:06] [Server thread/INFO]: [LiteBans] Disabling LiteBans v2.1.17
[19:29:06] [Server thread/INFO]: [LiteBans] v2.1.17 disabled.
[19:29:06] [Server thread/INFO]: [AuthMe] Disabling AuthMe v5.2-b1542
[19:29:06] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[19:29:06] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Close initiated...
[19:29:06] [Craft Scheduler Thread - 18/WARN]: [Craft Scheduler Thread - 18] WARN fr.xephi.authme.libs.zaxxer.hikari.pool.ProxyConnection - AuthMeMYSQLPool - Connection com.mysql.jdbc.JDBC4Connection@2534e243 marked as broken because of SQLSTATE(08S01), ErrorCode(0)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 363 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3082)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2968)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3516)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2273)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at fr.xephi.authme.libs.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at fr.xephi.authme.datasource.MySQL.getAllAuthsByIp(MySQL.java:686)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:229)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:88)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:52)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2529)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
[19:29:06] [Craft Scheduler Thread - 18/WARN]: 	... 18 more
[19:29:06] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Closed.
[19:29:06] [Server thread/INFO]: [AuthMe] AuthMe 5.2-b1542 disabled!
[19:29:06] [Craft Scheduler Thread - 18/WARN]: [AuthMe] Error during SQL operation: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 363 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
[19:29:06] [Server thread/INFO]: [Dubilets] Disabling Dubilets v1.5
[19:29:06] [Server thread/INFO]: [Dubilets]  Author adri1711 - desactivado
[19:29:06] [Server thread/INFO]: [TitleManager] Disabling TitleManager v1.5.12
[19:29:06] [Server thread/INFO]: [Vault] Disabling Vault v1.5.6-b49
[19:29:06] [Server thread/INFO]: [DonationsHolograms] Disabling DonationsHolograms v1.4
[19:29:06] [Craft Scheduler Thread - 18/WARN]: Exception in thread "Craft Scheduler Thread - 18" 
[19:29:06] [Server thread/INFO]: [CustomJoinItems] Disabling CustomJoinItems v1.5.2
[19:29:06] [Server thread/INFO]: [ScoreboardLobby] Disabling ScoreboardLobby v1.0
[19:29:06] [Server thread/INFO]: ScoreboardLobby Ha Sido Desabilitado!
[19:29:06] [Server thread/INFO]: [CommandPortals] Disabling CommandPortals v1.0.4
[19:29:06] [Server thread/INFO]: [SuperbVote] Disabling SuperbVote v0.3.2
[19:29:06] [Craft Scheduler Thread - 18/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-b1542 generated an exception while executing task 2147
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.ConsoleLogger.writeLog(ConsoleLogger.java:175)
	at fr.xephi.authme.ConsoleLogger.warning(ConsoleLogger.java:89)
	at fr.xephi.authme.ConsoleLogger.logException(ConsoleLogger.java:140)
	at fr.xephi.authme.datasource.MySQL.logSqlException(MySQL.java:970)
	at fr.xephi.authme.datasource.MySQL.getAllAuthsByIp(MySQL.java:692)
	at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:229)
	at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:88)
	at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:52)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

`

**Comment by sgdc3** [comment]
How many cores does your server (lobby, not mysql) have?

**Comment by Cazmon** [comment]
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, 8 cores

**Comment by Gnat008** [comment]
Not sure if relevant, but as a note, the i7-6400K is 4 cores, 8 threads. :)

**Comment by Cazmon** [comment]
Thanks, i copy the info from OVH

**Comment by sgdc3** [comment]
what happens with 100 as poolSize? @Cazmon

**Comment by Cazmon** [comment]
Ok, Testing... 100 PoolSize.

**Comment by Cazmon** [comment]
SQLException Error on stop the server: http://pastebin.com/9MVNuqSj

**Comment by Cazmon** [comment]
Other lobby: http://pastebin.com/9gthrNHb

**Comment by Cazmon** [comment]
The all lobbys freeze when some lobby restart. Errors on close server:

[22:24:40 INFO]: Saving chunks for level 'hub'/Overworld
[22:24:40 WARN]: [AuthMe] Error during SQL operation: [SQLException]: HikariDataSource HikariDataSource (AuthMeMYSQLPool) has been closed.
[22:24:40 WARN]: Exception in thread "Craft Scheduler Thread - 1492" 
[22:24:40 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-b1542 generated an exception while executing task 797640
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at fr.xephi.authme.ConsoleLogger.writeLog(ConsoleLogger.java:175)
        at fr.xephi.authme.ConsoleLogger.warning(ConsoleLogger.java:89)
        at fr.xephi.authme.ConsoleLogger.logException(ConsoleLogger.java:140)
        at fr.xephi.authme.datasource.MySQL.logSqlException(MySQL.java:970)
        at fr.xephi.authme.datasource.MySQL.isAuthAvailable(MySQL.java:240)
        at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:111)
        at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:76)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

>Its off..sleeping for 5
Para evitar que se ejecute de nuevo presione CTRL+C

**Comment by Cazmon** [comment]
[21:20:57 INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[21:20:57 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-b1542 generated an exception while executing task 1358265
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:119)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:102)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:85)
        at fr.xephi.authme.service.BukkitService.scheduleSyncDelayedTask(BukkitService.java:61)
        at fr.xephi.authme.service.BukkitService.scheduleSyncTaskFromOptionallyAsyncTask(BukkitService.java:86)
        at fr.xephi.authme.process.SyncProcessManager.runTask(SyncProcessManager.java:59)
        at fr.xephi.authme.process.SyncProcessManager.processSyncPlayerLogin(SyncProcessManager.java:51)
        at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:253)
        at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:88)
        at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:52)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[21:20:57 INFO]: [EssentialsChat] Disabling EssentialsChat vTeamCity

**Comment by Cazmon** [comment]
server freezer and not continue on start server

[21:24:49 INFO]: [AuthMe] Enabling AuthMe v5.2-b1542
[21:24:50 INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[21:24:50 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Started.
[21:24:50 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
>

**Comment by sgdc3** [comment]
@Cazmon any news?

**Comment by Cazmon** [comment]
same error on stop:

[21:20:57 INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[21:20:57 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-b1542 generated an exception while executing task 1358265
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:119)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:102)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:85)
at fr.xephi.authme.service.BukkitService.scheduleSyncDelayedTask(BukkitService.java:61)
at fr.xephi.authme.service.BukkitService.scheduleSyncTaskFromOptionallyAsyncTask(BukkitService.java:86)
at fr.xephi.authme.process.SyncProcessManager.runTask(SyncProcessManager.java:59)
at fr.xephi.authme.process.SyncProcessManager.processSyncPlayerLogin(SyncProcessManager.java:51)
at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:253)
at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:88)
at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:52)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more


and server freezer on enabling no more activity afer that:

[21:24:49 INFO]: [AuthMe] Enabling AuthMe v5.2-b1542
[21:24:50 INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[21:24:50 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Started.
[21:24:50 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)

**Comment by sgdc3** [comment]
@Cazmon That's another issue, could you open another issue for it? What about the database timeout?

**Comment by sgdc3** [comment]
@Cazmon Any news?

**Comment by nigxht** [comment]
you solved it?
