### ISSUE TITLE
The server crash

### ISSUE THREAD

**Issue by DoctorWh00** [AuthMe/AuthMeReloaded#1154]
I put the latest version of the plugin and when i try to start the server,it crash.
I use bungecoord but ONLY when i put
    SQLProblem:
        # Stop the server if we can't contact the sql database
        # Take care with this, if you set this to false,
        # AuthMe will automatically disable and the server won't be protected!
        stopServer: true

to false the server start but authme don't work,and is a sqlproblem
my authme.log
`[03-31 19:35:12]: [INFO] SQLite driver loaded
[03-31 19:35:12]: [INFO] SQLite Setup finished
[03-31 19:35:12]: [INFO] No supported permissions system found! Permissions are disabled!
[03-31 19:35:12]: [INFO] Hooked successfully into Essentials
[03-31 19:35:12]: [INFO] Hooked successfully into Multiverse-Core
[03-31 19:35:12]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[03-31 19:35:12]: fr.xephi.authme.libs.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjection.instantiateWith(ConstructorInjection.java:39)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:251)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:219)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:139)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.safeGetDeclaredFields(ReflectionUtils.java:177)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.validateHasNoOtherInjectAnnotations(ConstructorInjectionProvider.java:45)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:21)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:13)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.DirectInstantiationProvider.get(DirectInstantiationProvider.java:16)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:190)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:180)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:78)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:103)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more

[03-31 19:35:12]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[03-31 19:35:12]: [INFO] AuthMe 5.2-b1542 disabled!
[03-31 19:39:00]: [INFO] SQLite driver loaded
[03-31 19:39:00]: [INFO] SQLite Setup finished
[03-31 19:39:00]: [INFO] No supported permissions system found! Permissions are disabled!
[03-31 19:39:00]: [INFO] Hooked successfully into Essentials
[03-31 19:39:00]: [INFO] Hooked successfully into Multiverse-Core
[03-31 19:39:00]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[03-31 19:39:00]: fr.xephi.authme.libs.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjection.instantiateWith(ConstructorInjection.java:39)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:251)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:219)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:139)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: Lcom/google/gson/Gson;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.safeGetDeclaredFields(ReflectionUtils.java:177)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.validateHasNoOtherInjectAnnotations(ConstructorInjectionProvider.java:45)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:21)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.ConstructorInjectionProvider.safeGet(ConstructorInjectionProvider.java:13)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.DirectInstantiationProvider.get(DirectInstantiationProvider.java:16)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:190)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:180)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:225)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:183)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:78)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:103)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more

[03-31 19:39:00]: [INFO] AuthMe 5.2-b1542 disabled!
`
I receive this error also when i put the default config

**Comment by sgdc3** [comment]
What's your server version?

**Comment by DoctorWh00** [comment]
1.8 with viaversion

**Comment by ljacqu** [comment]
What server version? Like spigot, CraftBukkit...

**Comment by DoctorWh00** [comment]
Spigot

**Comment by Dimatert9** [comment]
@DoctorWh00  Why you use spigot 1.8.0/1? Use 1.8.8

**Comment by DoctorWh00** [comment]
Uhm,sincerely i don't know xD
The player with 1.8 can enter?

**Comment by Dimatert9** [comment]
Spigot 1.8.8 support all 1.8 versions(1.8-1.8.9)

**Comment by DoctorWh00** [comment]
If i put spigot 1.8.8,the latest version of authme will work?

**Comment by Dimatert9** [comment]
I think yes

**Comment by DoctorWh00** [comment]
I will test tomorrow

**Comment by ljacqu** [comment]
I think you just need to use the legacy Jar of AuthMe. See our Jenkins (linked on repo mainpage — I'm on mobile)

**Comment by sgdc3** [comment]
@ljacqu shouldn't it show a severe error in console if the wrong jar is used?

**Comment by ljacqu** [comment]
> AuthMe 5.2-b1542 

I added a warning with the hint to use legacy jar  but that was in 5.3 ^^

**Comment by sgdc3** [comment]
Ah ok ;)

**Comment by DoctorWh00** [comment]
I use the legacy version

**Comment by sgdc3** [comment]
@DoctorWh00 Is it working now?
