### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [AuthMe/AuthMeReloaded#1167]
log
```
[18:08:43 ERROR]: Could not load 'plugins/AuthMe-5.3-SNAPSHOT-spigot.jar' in folder 'pl
ugins'                                                                                 
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml                      
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoade
r.java:158) ~[patched_1.11.2.jar:git-Paper-1081]                                       
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:1
36) [patched_1.11.2.jar:git-Paper-1081]                                                
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:302
) [patched_1.11.2.jar:git-Paper-1081]                                                  
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:208)
 [patched_1.11.2.jar:git-Paper-1081]                                                   
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) 
[patched_1.11.2.jar:git-Paper-1081]                                                    
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]                         
Caused by: java.util.zip.ZipException: error in opening zip file                       
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]                    
        at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]               
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]               
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]               
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_121]               
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_121]               
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoade
r.java:146) ~[patched_1.11.2.jar:git-Paper-1081]                                       
        ... 5 more    
```
version
http://ci.xephi.fr/job/AuthMeReloaded/1651/

mysql mariadb
hash argon2
java 8 121 64bit

**Comment by jeremy100** [comment]
You .jar file is empty -> 0kb?

**Comment by ljacqu** [comment]
Please redownload the JAR and see if the problem persists

**Comment by mat41997** [comment]
thx.
