### ISSUE TITLE
AuthMe Error

### ISSUE THREAD

**Issue by IhaveanIssue** [AuthMe/AuthMeReloaded#1183]
I get this Error when I start my server and AuthMe does not work:
>
[15:00:54 WARN]: Exception in thread "Craft Scheduler Thread - 0" 
>
[15:00:54 WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.2-b1542 generated an exception while executing task 43
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
        at org.sqlite.Conn.prepareStatement(Conn.java:404)
        at org.sqlite.Conn.prepareStatement(Conn.java:399)
        at org.sqlite.Conn.prepareStatement(Conn.java:383)
        at fr.xephi.authme.datasource.SQLite.getAccountsRegistered(SQLite.java:538)
        at fr.xephi.authme.datasource.CacheDataSource.getAccountsRegistered(CacheDataSource.java:214)
        at fr.xephi.authme.initialization.DataSourceProvider.lambda$checkDataSourceSize$0(DataSourceProvider.java:89)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by ljacqu** [comment]
if you don't already use `logConsole: true` and share that authme.log. Also more info like how long this has been happening and if you have any suspicion (like a recent server update or so)

**Comment by ljacqu** [comment]
At a quick glance, looks like a different SQLite implementation that implements an older JDBC version.

**Comment by Dimatert9** [comment]
`v1_8_R1`
update your spigot to 1.8.8(Better to 1.11.2)

**Comment by ljacqu** [comment]
@IhaveanIssue Is it possible for you to update, as suggested?

**Comment by Xephi** [comment]
Bump @IhaveanIssue
