### ISSUE TITLE
error on torchspigot 1.11.2

### ISSUE THREAD

**Issue by mat41997** [AuthMe/AuthMeReloaded#1184]
logs
```
[04:57:50] [Server thread/WARN]: [AuthMe] Task #557 for AuthMe v5.3-SNAPSHOT-b1656 generated an exception
java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.saveData(CraftPlayer.java:645) ~[Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:95) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at org.torch.server.TorchServer.updateLogicsAndPhysics(TorchServer.java:902) [Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at org.torch.server.TorchServer.updateLogicsPhysicsExecuteCommands(TorchServer.java:1661) [Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at org.torch.server.TorchServer.tick(TorchServer.java:853) [Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at org.torch.server.TorchServer.run(TorchServer.java:544) [Torchpowered-1.11.2.jar:git-Torch-"0dd7bc40"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

timings
https://timings.aikar.co/?id=2ec1e12035bc44239abccfe5fa2c9014

torchspigot
https://github.com/TorchSpigot/Torch

**Comment by sgdc3** [comment]
Torchspigot isn't supported atm, does it work with normal spigot/paper?

**Comment by mat41997** [comment]
yes

**Comment by sgdc3** [comment]
Seems like a torchspigot issue
