### ISSUE TITLE
Error with new API event AbstractUnregisterEvent

### ISSUE THREAD

**Issue by TerZer** [AuthMe/AuthMeReloaded#1192]
I checked everything. It is not working because of AuthMe. Error:

```
[15:05:22 INFO]: [ServerioSirdis] Enabling ServerioSirdis v0.3
[15:05:22 ERROR]: Error occurred while enabling ServerioSirdis v0.3 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event fr.xephi.authme.events.CustomEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:586) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:528) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at lt.TerZer.ServerCore.Listiners.FirstTimeListener.<init>(FirstTimeListener.java:31) ~[?:?]
        at lt.TerZer.ServerCore.Main.loadListeners(Main.java:67) ~[?:?]
        at lt.TerZer.ServerCore.Main.onEnable(Main.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:750) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-54ec0b8-ac405c3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by games647** [comment]
AbstractUnregisterEvent is a abstract class without a handlerlist instance. You have to use the concrete class like UnregisterByAdminEvent or UnregisterByPlayerEvent

**Comment by ljacqu** [comment]
Do i see it correctly that you're listening to CustomEvent, and not some specific event?

**Comment by ljacqu** [comment]
Geez it's not possible to listen to an abstract method? I just tried now for the first time, and what a disappointment that is

**Comment by TerZer** [comment]
Hmm.. I am doing it wrong?
http://i.imgur.com/akrwIFm.png

**Comment by ljacqu** [comment]
Yes, see games' comment.
