### ISSUE TITLE
Could not load on Thermos 1.7.10 (Java 8)

### ISSUE THREAD

**Issue by Floroger** [AuthMe/AuthMeReloaded#1196]
Hello,

I'm trying to use the 5.2 legacy version but I've got a problem. 

I know that 5.2 need Java 8, I have updated my Debian Jessie server : 

>  java -version
>  openjdk version "1.8.0_121"
>  OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
>  OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

I'm on a 1.7.10 Minecraft serve, so I have downloaded this version of AuthMe : 
https://dev.bukkit.org/projects/authme-reloaded/files/2374441

When I launch Minecraft, the plugin file isn't created and I have errors on the log file : 

`[18:54:47] [Server thread/ERROR]: Could not load 'plugins/AuthMe-5.2-legacy.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `fr.xephi.authme.AuthMe'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:?]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: Failed to remap class fr.xephi.authme.AuthMe
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:?]
	... 12 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-4.1.jar:4.1]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-4.1.jar:4.1]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-4.1.jar:4.1]
	at net.md_5.specialsource.RemapperProcessor.process(RemapperProcessor.java:83) ~[RemapperProcessor.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:444) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:?]`

Where is the problem ?

Many thanks.

**Comment by sgdc3** [comment]
Does it happen with that? http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.3-SNAPSHOT-legacy.jar

**Comment by Floroger** [comment]
Yes exactly the same error message.

**Comment by sgdc3** [comment]
@ljacqu :/ connot find main class... a corruptedd download... twice?!

**Comment by ljacqu** [comment]
Hi @Floroger, do you use Java 7 per chance? We switched to Java 8 a while ago and unfortunately don't support Java 7 anymore.

What caught my eye is "Failed to remap class" in the stack trace, and when searching for this Google will even suggest a search of this with "Bukkit."

**Comment by games647** [comment]
In case you use Thermos, Cauldron or similar, you have to update the SpecialSource library to support Java 8 plugins.

**Comment by Floroger** [comment]
I'm using cauldron yes. I have installed the Legacy Java Fixer. What is the SpecialSource ?

**Comment by sgdc3** [comment]
> In case you use Thermos, Cauldron or similar, you have to update the SpecialSource library to support Java 8 plugins.

Thank you, i'll add that to the main page ;)

**Comment by games647** [comment]
https://github.com/games647/FastLogin/issues/111#issuecomment-272331347

I think this one is simple enough.

**Comment by sgdc3** [comment]
Thank you
