### ISSUE TITLE
Plugin does not work with CraftBukkit 1.11.2

### ISSUE THREAD

**Issue by farizluqman** [AuthMe/AuthMeReloaded#1216]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
Craftbukkit 1.11.2, AuthMe version 5.2
https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.11.2.jar

### What behaviour is observed:
This plugin does not work at all on CraftBukkit 1.11.2.

### What behaviour is expected:
I expect it to work, obviously

### Steps/models to reproduce:
Simply run the Craftbukkit server

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server

### AuthMe build number:
This can be found by running `/authme version`
- command not found

### Error Log:
[00:12:49] [Server thread/ERROR]: Could not load 'plugins/AuthMe-5.2-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : Unsupported major.minor version 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Bukkit-fcc5dcc]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-fcc5dcc]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:298) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:260) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-fcc5dcc]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.UnsupportedClassVersionError: fr/xephi/authme/AuthMe : Unsupported major.minor version 52.0

### Configuration:
Not exist

**Comment by farizluqman** [comment]
Confirmed that using Spigot 1.11.2 with Java 1.8 worked. 

Ditched CraftBukkit for good :)

**Comment by sgdc3** [comment]
The issue was java, we still support craftbukkit ;)
