### ISSUE TITLE
Thermos: NoClassDefFound: HikariPool

### ISSUE THREAD

**Issue by l89669** [AuthMe/AuthMeReloaded#1231]
Newest Authme on CI
Server: Thermos 58, Minecraft1.7.10, Forge 1614, running upon jdk1.8.0_111, Centos 7.6
Config: mysql enabled

**Comment by l89669** [comment]
[17:44:59] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Enabling AuthMe v5.3-SNAPSHOT
[17:45:00] [Server thread/INFO] [fr.xephi.authme.AuthMe/]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[17:45:00] [Server thread/WARN] [/]: [Server thread] INFO com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[17:45:00] [Server thread/WARN] [fr.xephi.authme.AuthMe/]: [AuthMe] Aborting initialization of AuthMe: [NoClassDefFoundError]: com/zaxxer/hikari/pool/HikariPool
[17:45:00] [Server thread/WARN] [fr.xephi.authme.AuthMe/]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!

**Comment by ljacqu** [comment]
Can you try with the -legacy.jar please?

**Comment by l89669** [comment]
Actually I'm using the legacy jar because I'm running 1.7.10.

**Comment by ljacqu** [comment]
@sgdc3 Do we support Thermos? I just tried and it indeed doesn't work, I'm getting an error about a shaded in library. I'm not really willing to spend a lot of time on this at the moment, though

**Comment by l89669** [comment]
5.2 is working well, but since somewhere at 5.3 the problem showed up :/

**Comment by l89669** [comment]
It's just about the hikari connection pool dependency because the plugin works perfectly without mysql enabled.

**Comment by l89669** [comment]
And because the code was written to not let the stacktrace to be printed, I can't look into the code and find the bug :/

**Comment by l89669** [comment]
A little idea: 
because the exception is a NoClassDefFoundException, and the printed classpath is not the same as shaded classpath,so the problem maybe in somewhere using reflection that the shading plugin can't handle or Thermos reflection utils get confused?

**Comment by ljacqu** [comment]
We don't shade HikariCP. My guess is ~we updated the version during the development of 5.3 and now it no longer corresponds with Thermos?~ HikariCP is no longer shipped with Thermos, maybe they removed that dependency

**Comment by l89669** [comment]
You mean the HikariCP should be delivered with server libraries? That case an upgrade of it will eassily cause the problem :/

**Comment by l89669** [comment]
Tomorrow (China time) I'll try add the library jar into plugins to see if it works.

**Comment by l89669** [comment]
I'm a little confused because I DID SEE shading code of com.zaxxer.hikari.pool in pom.xml, both spigot and legacy have the code.

**Comment by l89669** [comment]
Another hint: the New version of HikariCP itself used reflection or something that the shading plugin can't cover. But it's strange that it only happens on Thermos. Anyway, not showing the stacktrace really troubles me...

**Comment by ljacqu** [comment]
authme.log shows stacktrace with the right settings https://github.com/AuthMe/AuthMeReloaded/wiki/Configuring-logging

**Comment by l89669** [comment]
Thats really a surprise...

**Comment by sgdc3** [comment]
We DO shade and RELOCATE HikariCP!

**Comment by l89669** [comment]
so thats more likly to be a reflection problem. Btw I do find some Class.forName code but still can't find code about HikariCP.

**Comment by l89669** [comment]
# So here's the stacktrace
[05-29 16:04:19]: java.lang.NoClassDefFoundError: fr/xephi/authme/libs/zaxxer/hikari/pool/HikariPool
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:168)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:78)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:70)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:46)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:257)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:232)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:140)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Failed to remap class fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246)
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232)
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499)
	... 29 more

**Comment by l89669** [comment]
Solved. Anyone uses Thermos can manually update your specialsource (in libraries) to 1.7.4 to solve it.
Paste update files here. Just unzip it and replace the existing files in libraries/net/md-5/SpecialSource/1.7-SNAPSHOT/
[SpecialSource-1.7.4.zip](https://github.com/AuthMe/AuthMeReloaded/files/1052526/SpecialSource-1.7.4.zip)
Please don't close this issue. I want to let others know how to solve it.

**Comment by games647** [comment]
@l89669 This was already posted here: #1196

**Comment by l89669** [comment]
weired. 5.2 version works well on my machine.
