### ISSUE TITLE
NoClassDefFoundError on Spigot 1.11.2

### ISSUE THREAD

**Issue by jeremy100** [AuthMe/AuthMeReloaded#1239]
**The ERROR:**
Plugins: none, only AuthMe-5.3 Stable on Spigot web plugin
DB Connection: MySQL Remote

PS: The version I use that works me correctly is "AuthMe-5.3-#1653-spigot" of Jenkins.

[00:43:55] [Craft Scheduler Thread - 12/WARN]: [AuthMe] Plugin AuthMe v5.3-b1697 generated an exception while executing task 103
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at fr.xephi.authme.datasource.CacheDataSource.getAuth(CacheDataSource.java:90) ~[?:?]
	at fr.xephi.authme.process.login.AsynchronousLogin.getPlayerAuth(AsynchronousLogin.java:115) ~[?:?]
	at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:82) ~[?:?]
	at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:53) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at fr.xephi.authme.data.auth.PlayerAuth$Builder.build(PlayerAuth.java:245) ~[?:?]
	at fr.xephi.authme.datasource.MySQL.buildAuthFromResultSet(MySQL.java:983) ~[?:?]
	at fr.xephi.authme.datasource.MySQL.getAuth(MySQL.java:307) ~[?:?]
	at fr.xephi.authme.datasource.CacheDataSource$1.load(CacheDataSource.java:53) ~[?:?]
	at fr.xephi.authme.datasource.CacheDataSource$1.load(CacheDataSource.java:50) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at fr.xephi.authme.data.auth.PlayerAuth$Builder.build(PlayerAuth.java:245) ~[?:?]

**Comment by Xephi** [comment]
Please use Legacy version for Minecraft 1.11

**Comment by sgdc3** [comment]
We should add an explicit severe error. @Xephi @ljacqu

**Comment by ljacqu** [comment]
I'll do it
