### ISSUE TITLE
Error while registering

### ISSUE THREAD

**Issue by marcopaggioro** [AuthMe/AuthMeReloaded#1240]
Server start as well but when i try to register i can see this error in console. Default configuration. Debian 8 with java-8.

[AuthMe] Plugin AuthMe v5.3.1-b1702 generated an exception while executing task 13
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
        at fr.xephi.authme.data.auth.PlayerAuth$Builder.build(PlayerAuth.java:245) ~[?:?]
        at fr.xephi.authme.process.register.executors.PlayerAuthBuilderHelper.createPlayerAuth(PlayerAuthBuilderHelper.java:32) ~[?:?]
        at fr.xephi.authme.process.register.executors.PasswordRegisterExecutor.createPlayerAuthObject(PasswordRegisterExecutor.java:14) ~[?:?]
        at fr.xephi.authme.process.register.executors.PasswordRegisterExecutor.createPlayerAuthObject(PasswordRegisterExecutor.java:10) ~[?:?]
        at fr.xephi.authme.process.register.executors.AbstractPasswordRegisterExecutor.buildPlayerAuth(AbstractPasswordRegisterExecutor.java:66) ~[?:?]
        at fr.xephi.authme.process.register.executors.AbstractPasswordRegisterExecutor.buildPlayerAuth(AbstractPasswordRegisterExecutor.java:23) ~[?:?]
        at fr.xephi.authme.process.register.AsyncRegister.executeRegistration(AsyncRegister.java:84) ~[?:?]
        at fr.xephi.authme.process.register.AsyncRegister.register(AsyncRegister.java:54) ~[?:?]
        at fr.xephi.authme.process.Management.lambda$performRegister$3(Management.java:65) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[jar_spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [jar_spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[jar_spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[jar_spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        ... 14 more

**Comment by Twonox** [comment]
Use that verion: http://ci.xephi.fr/job/AuthMeReloaded/1704/
