### ISSUE TITLE
AuthME warn bug

### ISSUE THREAD

**Issue by SeussCZ** [AuthMe/AuthMeReloaded#1249]
Hi, can someone help me with this plugin? when i want to use command /register pw pw, in console is WARN and nothing happend. Thanks

AuthMe Reloaded 5.3.1 Release

[23:59:01] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5"
[23:59:01] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.3.1-b1702 generated an exception while executing task 172
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
    at fr.xephi.authme.data.auth.PlayerAuth$Builder.build(PlayerAuth.java:245)
    at fr.xephi.authme.process.register.executors.PlayerAuthBuilderHelper.createPlayerAuth(PlayerAuthBuilderHelper.java:32)
    at fr.xephi.authme.process.register.executors.PasswordRegisterExecutor.createPlayerAuthObject(PasswordRegisterExecutor.java:14)
    at fr.xephi.authme.process.register.executors.PasswordRegisterExecutor.createPlayerAuthObject(PasswordRegisterExecutor.java:10)
    at fr.xephi.authme.process.register.executors.AbstractPasswordRegisterExecutor.buildPlayerAuth(AbstractPasswordRegisterExecutor.java:66)
    at fr.xephi.authme.process.register.executors.AbstractPasswordRegisterExecutor.buildPlayerAuth(AbstractPasswordRegisterExecutor.java:23)
    at fr.xephi.authme.process.register.AsyncRegister.executeRegistration(AsyncRegister.java:84)
    at fr.xephi.authme.process.register.AsyncRegister.register(AsyncRegister.java:54)
    at fr.xephi.authme.process.Management.lambda$performRegister$3(Management.java:65)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more

**Comment by sgdc3** [comment]
You have to use the legacy jar on 1.8: http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.3.2-SNAPSHOT-legacy.jar
