### ISSUE TITLE
console error authme version 5.3.1

### ISSUE THREAD

**Issue by friishon** [AuthMe/AuthMeReloaded#1252]
i have this error on console
i use spigot 1.11.2

[13:50:24 ERROR]: Could not pass event PlayerLoginEvent to AuthMe v5.3.1-b1702
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.PlayerList.attemptLogin(PlayerList.java:502) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:121) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at fr.xephi.authme.datasource.CacheDataSource.getAuth(CacheDataSource.java:90) ~[?:?]
        at fr.xephi.authme.listener.PlayerListener.onPlayerLogin(PlayerListener.java:220) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        ... 13 more

**Comment by sgdc3** [comment]
You have to use the legacy jar

**Comment by Eufranio** [comment]
Legacy jar in 1.11.2 Spigot?

**Comment by friishon** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/
here you can found
http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.3.2-SNAPSHOT-legacy.jar
