### ISSUE TITLE
Authme spawns players to another world

### ISSUE THREAD

**Issue by MuhammedKpln** [AuthMe/AuthMeReloaded#1260]
### What behaviour is observed:
What happened?

On first join when they are done with register, it teleports to another world named "world". But in multiverse, essentials and authme i have setspawn to world named "lobi". 

### What behaviour is expected:
What did you expect?

It should spawn players where i did setspawn, but i won't work like what i want.

### Steps/models to reproduce:
The actions that cause the issue

register

### Plugin list:
This can be found by running `/pl`

No, it cant

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

Mysql server

### AuthMe build number:
This can be found by running `/authme version`

Build 1697

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
http://paste.ubuntu.com/24917429/
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
http://paste.ubuntu.com/24917435/

**Comment by ljacqu** [comment]
A lot of stuff going on, at 15:55:33 your config.yml became invalid.

Before that I see a serious issue:

> [06-17 05:08:25]: java.sql.SQLException: Column 'id' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1144)
	at com.mysql.jdbc.ResultSetImpl.getInt(ResultSetImpl.java:2813)
	at fr.xephi.authme.libs.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java)
	at fr.xephi.authme.datasource.MySQL.getAuth(MySQL.java:309)
	at fr.xephi.authme.datasource.CacheDataSource$1.load(CacheDataSource.java:49)
	at fr.xephi.authme.datasource.CacheDataSource$1$1.call(CacheDataSource.java:58)
	at fr.xephi.authme.datasource.CacheDataSource$1$1.call(CacheDataSource.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

AuthMe stores a DB ID for each account and it seems like your table doesn't have the "id" column

Also please run `/authme messages` as the error message that keeps popping up is telling you. Then it will shut up.

I don't know if afterwards it will fix the teleport problem. You can find the configurations explained at https://github.com/AuthMe/AuthMeReloaded/wiki/Spawn-Handling If there's anything that doesn't behave as described on that page, then we have a bug.

**Comment by MuhammedKpln** [comment]
It isn't something to do with id column, because im using userid instead id. And it works correctly i dont think the world teleporting isn't something to do with mysql.

**Comment by MuhammedKpln** [comment]
The problam seesm to be fixed by resetting the config file

**Comment by ljacqu** [comment]
Thanks for the update, sorry I didn't get around to trying to reproduce this. Voting to close this for now, but again, if you find anything that diverges from the Wiki page I linked to, your report is much appreciated. Thanks
