### ISSUE TITLE
Missing shading execution

### ISSUE THREAD

**Issue by T1MOXA** [AuthMe/AuthMeReloaded#1264]
```
Error occurred while enabling AuthMe v5.3.2-SNAPSHOT-b1712 (Is it up to date?)
java.lang.NoClassDefFoundError: net/ricecode/similarity/SimilarityStrategy
	at fr.xephi.authme.ConsoleLogger.logException(ConsoleLogger.java:103) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched.jar:git-TacoSpigot-"22b1d457"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.ricecode.similarity.SimilarityStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-TacoSpigot-"22b1d457"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	... 13 more
```

**Comment by ljacqu** [comment]
@sgdc3 Something is not right with the relocation, even in older builds (e.g. 1688) the dependencies are shaded in with the original package, and the relocations to fr.xephi.libs have no effect. Could you help? I'm at a loss here. :/

**Comment by ljacqu** [comment]
Shading works now but relocation still doesn't

**Comment by sgdc3** [comment]
Have you tried it? It seems to be working.

**Comment by sgdc3** [comment]
There are some packages that we don't shade due to incompatibilities, (the email library for example)

**Comment by ljacqu** [comment]
Thanks for the fix! I had a closer look at the JAR and you're right—only a select few libraries are not shaded. My bad, sorry. I didn't expect there to be so much.

JAR can be run successfully again, so I close this issue.
