### ISSUE TITLE
NoClassDefFoundError for PlayerSpawnLocationEvent on Uranium (KCauldron)

### ISSUE THREAD

**Issue by SourcePowered** [AuthMe/AuthMeReloaded#1341]
Uranium 1.7.10 - B172 ( A KCauldron fork https://ci.xjboss.net/job/Uranium-dev/ )
Authme Build 1797

First time:
```
[19:50:32] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.4-SNAPSHOT-b1797
[19:50:34] [Server thread/INFO]: [AuthMe] SQLite driver loaded
[19:50:35] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[19:50:36] [Server thread/INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[19:50:38] [Server thread/WARN]: [AuthMe] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[19:50:38] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [NoClassDefFoundError]: org/spigotmc/event/player/PlayerSpawnLocationEvent
[19:50:38] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[19:50:38] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[19:50:38] [Server thread/INFO]: [AuthMe] AuthMe 5.4-SNAPSHOT-b1797 disabled!
```

Then I set some thing to "false", and next time:

```
[19:44:29] [Craft Scheduler Thread - 2/WARN]: org.apache.commons.lang.UnhandledException: Plugin AuthMe v5.4-SNAPSHOT-b1797 generated an exception while executing task 46
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.sqlite.PrepStmt.<init>(PrepStmt.java:42)
	at org.sqlite.Conn.prepareStatement(Conn.java:404)
	at org.sqlite.Conn.prepareStatement(Conn.java:399)
	at org.sqlite.Conn.prepareStatement(Conn.java:383)
	at fr.xephi.authme.datasource.SQLite.getAccountsRegistered(SQLite.java:484)
	at fr.xephi.authme.datasource.CacheDataSource.getAccountsRegistered(CacheDataSource.java:219)
	at fr.xephi.authme.initialization.DataSourceProvider.lambda$checkDataSourceSize$0(DataSourceProvider.java:95)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**The old version did not have this problem.**

**Comment by MineSAT** [comment]
It seems that Authme is not compatible with KCauldron :/

**Comment by SourcePowered** [comment]
YES, sir. I will using 5.3.2 or ... 3.4...

**Comment by sgdc3** [comment]
@MineSAT It is compatible, that is caused by a recent commit, i'll fix this asap ;)

**Comment by ljacqu** [comment]
Review:
- Does the new event really belong in the 1.9 listener? The package name suggests it's specific to Spigot: `org.spigotmc.event.player.PlayerSpawnLocationEvent`. Suggestion: add to a new "SpigotPlayerListener" (or similar) and determine with `Utils#isClassLoaded` which option to choose.
- `IS_ASYNC_PLAYER_PRE_LOGIN_EVENT_CALLED` is not immutable and so should not be in uppercase.
- `isIsPlayerSpawnLocationEventCalled` weird method name -> `isPlayerSpawnLocationEventCalled` would be enough. It's OK that the method name has the same name as the field in this case.

**Comment by sgdc3** [comment]
Lol i missed all that points, you're 100% right xD

**Comment by sgdc3** [comment]
@ljacqu is it ok now?

**Comment by ljacqu** [comment]
@sgdc3 Thanks, looks good and successfully tested with Bukkit 1.8.8. I close.
