### ISSUE TITLE
Player IP retrieval causes NullPointerException on local server

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1365]
When I am running AuthMe on localhost it spits the following error each time I join. Apparently the IP lookup fails when the player's IP is looked up via Spigot's PlayerSpawnLocationEvent. 

```
[17:36:55 ERROR]: Could not pass event PlayerSpawnLocationEvent to AuthMe v5.4-SNAPSHOT-b1828
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:117) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at fr.xephi.authme.util.PlayerUtils.getPlayerIp(PlayerUtils.java:40) ~[?:?]
	at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:83) ~[?:?]
	at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:78) ~[?:?]
	at fr.xephi.authme.service.BukkitService.runTaskOptionallyAsync(BukkitService.java:128) ~[?:?]
	at fr.xephi.authme.process.Management.runTask(Management.java:102) ~[?:?]
	at fr.xephi.authme.process.Management.performJoin(Management.java:78) ~[?:?]
	at fr.xephi.authme.listener.PlayerListener19Spigot.onPlayerSpawn(PlayerListener19Spigot.java:34) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	... 13 more
```

**Comment by ljacqu** [comment]
Verified successfully -> closing. Thanks @sgdc3 :)
