### ISSUE TITLE
mysql does not connect help-me

### ISSUE THREAD

**Issue by EduardoMGP** [AuthMe/AuthMeReloaded#1383]
Hello, I'm not able to put authme in mysql
I did not find a solution on any ticket
At least if there is one I can not find

the error is as follows

```
WARN INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Started.
28.10 03:22:56 [Server] WARN Could not create data source: [PoolInitializationException]: Failed to initialize pool: Cannot connect to MySQL server on 192.99.21.28:3306.
28.10 03:22:56 [Server] INFO Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.
28.10 03:22:56 [Server] WARN Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
```

```
DataSource:
    # What type of database do you want to use?
    # Valid values: sqlite, mysql
    backend: 'MYSQL'
    # Enable database caching, should improve database performance
    caching: true
    # Database host address
    mySQLHost: '192.99.21.28'
    # Database port
    mySQLPort: '3306'
    # Username about Database Connection Infos
    mySQLUsername: 'mc1702'
    # Password about Database Connection Infos
    mySQLPassword: 'my password'
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: 'mc1702'
    # Table of the database
    mySQLTablename: 'authme'
    # Column of IDs to sort data
    mySQLColumnId: 'id'
    # Column for storing or checking players nickname
    mySQLColumnName: 'username'
    # Column for storing or checking players RealName
    mySQLRealName: 'realname'
    # Column for storing players passwords
    mySQLColumnPassword: 'password'
    # Request mysql over SSL
    mySQLUseSSL: true
    # Column for storing players emails
    mySQLColumnEmail: 'email'
    # Column for storing if a player is logged in or not
    mySQLColumnLogged: 'isLogged'
    # Column for storing players ips
    mySQLColumnIp: 'ip'
    # Column for storing players lastlogins
    mySQLColumnLastLogin: 'lastlogin'
    # Column for storing player LastLocation - X
    mySQLlastlocX: 'x'
    # Column for storing player LastLocation - Y
    mySQLlastlocY: 'y'
    # Column for storing player LastLocation - Z
    mySQLlastlocZ: 'z'
    # Column for storing player LastLocation - World Name
    mySQLlastlocWorld: 'world'
    # Overrides the size of the DB Connection Pool, -1 = Auto
    poolSize: -1
```

How can I make it work?
sorry if duplicated
I really did not find it to connect

**Comment by sgdc3** [comment]
> 192.99.21.28
Are you sure this is the right ip?

**Comment by EduardoMGP** [comment]
yes I have
utilizo um plugin em mysql
desta forma
jdbc:mysql://localhost:3306/mc1702
e funciona corretamente
o authme nem colocando localhost funciona 
http://prntscr.com/h38ib9

**Comment by ljacqu** [comment]
It's not connecting to the MySQL database. That's all we can tell you. Either the info is wrong, or your server can't make the connection to the MySQL DB, or the MySQL DB is not accepting your request.

**Comment by games647** [comment]
@EduardoMGP Could you post the content of the authme log file. There should be an exception stacktrace. Maybe it gives some more details like invalid credentials.

**Comment by EduardoMGP** [comment]
@games647 
`[09-07 21:18:23]: fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Cannot connect to MySQL server on 192.99.21.28:3306.

Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.


	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:151)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:155)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:43)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:24)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:138)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:248)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:219)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:139)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot connect to MySQL server on 192.99.21.28:3306.

Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:827)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
	... 26 more
Caused by: java.lang.UnsupportedOperationException: The method shutdownInput() is not supported in SSLSocket
	at sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:215)
	at com.mysql.jdbc.MysqlIO.forceClose(MysqlIO.java:506)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2404)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	... 38 more

[09-07 21:18:23]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[09-07 21:18:23]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:46)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:24)
	at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:138)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:184)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:162)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:248)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:219)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:139)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)
Caused by: fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Cannot connect to MySQL server on 192.99.21.28:3306.

Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.


	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105)
	at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:151)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:155)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:72)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:43)
	... 19 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Cannot connect to MySQL server on 192.99.21.28:3306.

Make sure that there is a MySQL server running on the machine/port you are trying to connect to and that the machine this software is running on is able to connect to this host/port (i.e. not firewalled). Also make sure that the server has not been started with the --skip-networking flag.


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:827)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
	... 26 more
Caused by: java.lang.UnsupportedOperationException: The method shutdownInput() is not supported in SSLSocket
	at sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:215)
	at com.mysql.jdbc.MysqlIO.forceClose(MysqlIO.java:506)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2404)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
	... 38 more`

**Comment by games647** [comment]
Try to disable useSSL and please format the log here.

**Comment by EduardoMGP** [comment]
@games647 
that's how it worked
but not converting the file to mysql
I have more than 16k registered users
I can not lose them
plus the conversion command is not converting
the authme database is converting the mc1702 database
more this database was created when dei reload


`DataSource:
    # What type of database do you want to use?
    # Valid values: sqlite, mysql
    backend: 'mysql'
    # Enable database caching, should improve database performance
    caching: true
    # Database host address
    mySQLHost: '192.99.21.28'
    # Database port
    mySQLPort: '3306'
    # Username about Database Connection Infos
    mySQLUsername: 'mc1702'
    # Password about Database Connection Infos
    mySQLPassword: '....'
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: 'mc1702'
    # Table of the database
    mySQLTablename: 'authme'
    # Column of IDs to sort data
    mySQLColumnId: 'id'
    # Column for storing or checking players nickname
    mySQLColumnName: 'username'
    # Column for storing or checking players RealName
    mySQLRealName: 'realname'
    # Column for storing players passwords
    mySQLColumnPassword: 'password'
    # Request mysql over SSL
    mySQLUseSSL: false`

if I put this mySQL Database: 'mc 1702'
as mc 1702 it creates a databse separate from what already exists
but if I put authme it returns me this error

`29.10 23:24:28 [Server] INFO Enabling AuthMe v5.2-b1542
29.10 23:24:29 [Server] INFO Connection arguments loaded, Hikari ConnectionPool ready!
29.10 23:24:29 [Server] WARN INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Started.
29.10 23:24:29 [Server] WARN Could not create data source: [PoolInitializationException]: Failed to initialize pool: Access denied for user 'mc1702'@'%' to database 'authme'
29.10 23:24:29 [Server] WARN Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source`

**Comment by games647** [comment]
>Access denied for user 'mc1702'@'%' to database 'authme'

Invalid username/password combination or this user account has no access to the database authme.

**Comment by EduardoMGP** [comment]
If I put mc1702 it works
More if you put authme of this mistake
How to pass the database to mysql without losing registered users?
The / authme converter is not passing the authme database the default that comes in the plugin

**Comment by games647** [comment]
So what are you trying to do? The plugin starts up without any issues and then your trying to convert the database and this error pops up? What was the exact command you typed in?
