### ISSUE TITLE
Bungeecord warning on login

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1401]
Latest dev build with `bungeecord: false` in config.yml, on login the following error is thrown

```
[10:13:33 WARN]: [AuthMe] Plugin AuthMe v5.4-SNAPSHOT-bCUSTOM generated an exception while executing task 40
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:482) ~[spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.sendPluginMessage(CraftServer.java:1493) ~[spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at fr.xephi.authme.service.BukkitService.sendPluginMessage(BukkitService.java:368) ~[?:?]
	at fr.xephi.authme.service.bungeecord.BungeeService.sendBungeecordMessage(BungeeService.java:64) ~[?:?]
	at fr.xephi.authme.service.bungeecord.BungeeService.sendAuthMeBungeecordMessage(BungeeService.java:93) ~[?:?]
	at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:229) ~[?:?]
	at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:93) ~[?:?]
	at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:54) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot_server.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by ljacqu** [comment]
Ah, it's my fault
