### ISSUE TITLE
Error when configured command is run after player unregisters

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeReloaded#1413]
1. When you log on to the server, you immediately output two messages with the keys: valid_session and login. This needs to be corrected.
2. After authorization on the server, the plugin teleports to the survival and writes that the session is saved. This message should not be displayed after authorization.
3. The /logout command must be teleported to the authorization server if AuthMeBridge is used.

**Comment by DarkFort** [comment]
and error
[01:16:24] [Server thread/INFO]: DarkFort issued server command: /authme unregister DarkFort
[01:16:25] [Craft Scheduler Thread - 406/WARN]: [Craft Scheduler Thread - 406] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[01:16:25] [Craft Scheduler Thread - 406/WARN]: [Craft Scheduler Thread - 406] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Start completed.
[01:16:25] [Craft Scheduler Thread - 406/ERROR]: Command Dispatched Async: kick DarkFort Ваш аккаунт был удален!
[01:16:25] [Craft Scheduler Thread - 406/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:658) ~[PaperSpigot.jar:git-Paper-1257]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:590) ~[PaperSpigot.jar:git-Paper-1257]
	at fr.xephi.authme.service.BukkitService.dispatchConsoleCommand(BukkitService.java:326) ~[?:?]
	at fr.xephi.authme.settings.commandconfig.CommandManager.executeCommands(CommandManager.java:110) ~[?:?]
	at fr.xephi.authme.settings.commandconfig.CommandManager.runCommandsOnUnregister(CommandManager.java:94) ~[?:?]
	at fr.xephi.authme.process.unregister.AsynchronousUnregister.performPostUnregisterActions(AsynchronousUnregister.java:123) ~[?:?]
	at fr.xephi.authme.process.unregister.AsynchronousUnregister.adminUnregister(AsynchronousUnregister.java:96) ~[?:?]
	at fr.xephi.authme.process.Management.lambda$performUnregisterByAdmin$5(Management.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [PaperSpigot.jar:git-Paper-1257]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot.jar:git-Paper-1257]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot.jar:git-Paper-1257]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_152]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
[01:16:25] [Craft Scheduler Thread - 385/INFO]: TomatoGUARD >> Вы не можете кикнуть darkfort.
[01:16:25] [Craft Scheduler Thread - 406/INFO]: [AuthMe] DarkFort was unregistered by DarkFort
[01:16:33] [Craft Scheduler Thread - 386/INFO]: [AuthMe] The user DarkFort has 4 accounts:
[01:16:33] [Craft Scheduler Thread - 386/INFO]: [AuthMe] fastplace, fassss, gared, DarkFort.
[01:16:33] [Craft Scheduler Thread - 386/INFO]: [AuthMe] DarkFort logged in!
[01:16:33] [Server thread/INFO]: [AuthMe] DarkFort registered 127.0.0.1

**Comment by sgdc3** [comment]
Stop using AuthMeBridge, use AuthMeBungee instead, you can download it from http://ci.xephi.fr/job/AuthMeBungee/

**Comment by sgdc3** [comment]
3) Please open a new issue for that, we never had such a feature,  you have to open a separate feature request

**Comment by sgdc3** [comment]
Please use pastebin or hastebin to post your errors/stacktraces.

**Comment by DarkFort** [comment]
https://hastebin.com/lotizeselo.sql

**Comment by ljacqu** [comment]
What's your commands.yml?

**Comment by DarkFort** [comment]
https://hastebin.com/qedireriwe.bash

**Comment by sgdc3** [comment]
@ljacqu Any idea?

**Comment by ljacqu** [comment]
> [01:16:25] [Craft Scheduler Thread - 406/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C

The link says not to run commands in async. The stacktrace (`AsynchronousUnregister.performPostUnregisterActions`) shows that it's what we're doing ;) 

I'll take care of this and verify that no other commands are being run from async.

**Comment by ljacqu** [comment]
hi @DarkFort, the command error is fixed with build n. 1872 or above at http://ci.xephi.fr/job/AuthMeReloaded/
If you could kindly give us a quick feedback that it works on your side, that would be swell
As for the other stuff I invite you to create new issues (one item at a time so we can properly track them). Thanks

**Comment by sgdc3** [comment]
@DarkFort any news? ;)

**Comment by DarkFort** [comment]
1. Not corrected
2. Not corrected
3. Not corrected

**Comment by ljacqu** [comment]
read above

> As for the other stuff I invite you to create new issues (one item at a time so we can properly track them)
