### ISSUE TITLE
Task Error on Spigot 1.12.2& and Java 8.

### ISSUE THREAD

**Issue by TheIntelloBox** [AuthMe/AuthMeReloaded#1440]
[18:35:33] [Server thread/WARN]: [AuthMe] Task #39743 for AuthMe v5.5.0-SNAPSHOT-b1884 generated an exception
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_72]
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[?:1.8.0_72]
	at java.util.Arrays.asList(Arrays.java:3800) ~[?:1.8.0_72]
	at fr.xephi.authme.permission.handlers.VaultHandler.getGroups(VaultHandler.java:79) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
	at fr.xephi.authme.permission.handlers.VaultHandler.getGroups(VaultHandler.java:19) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
	at fr.xephi.authme.permission.PermissionsManager.getGroups(PermissionsManager.java:295) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
	at fr.xephi.authme.data.limbo.LimboServiceHelper.createLimboPlayer(LimboServiceHelper.java:47) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
	at fr.xephi.authme.data.limbo.LimboService.createLimboPlayer(LimboService.java:70) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
	at fr.xephi.authme.process.join.AsynchronousJoin.lambda$processJoinSync$6(AsynchronousJoin.java:160) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by sgdc3** [comment]
What's your permission plugin?

**Comment by TheIntelloBox** [comment]
Group Manager.

**Comment by ljacqu** [comment]
@sgdc3 Any news on this?

**Comment by sgdc3** [comment]
@ljacqu GroupManager is very outdated and doesn't implement all the group api stuff, people should stop using it.

**Comment by ljacqu** [comment]
I'll have a look at this

**Comment by ljacqu** [comment]
This has been fixed with #1702 a long time ago.
