### ISSUE TITLE
Latest build does not start

### ISSUE THREAD

**Issue by Dimatert9** [AuthMe/AuthMeReloaded#1481]
```
[22:33:50] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.5.0-SNAPSHOT-b1916
[22:33:50] [Server thread/ERROR]: Error occurred while enabling AuthMe v5.5.0-SNAPSHOT-b1916 (Is it up to date?)
java.lang.NoClassDefFoundError: net/ricecode/similarity/SimilarityStrategy
	at fr.xephi.authme.ConsoleLogger.logException(ConsoleLogger.java:104) ~[?:?]
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1310]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: net.ricecode.similarity.SimilarityStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1310]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 13 more
[22:33:50] [Server thread/INFO]: [AuthMe] Disabling AuthMe v5.5.0-SNAPSHOT-b1916
```
No plugins installed, latest paperspigot build

**Comment by sgdc3** [comment]
Use the shaded jar in the meantime

**Comment by ljacqu** [comment]
@sgdc3 Can we remove the regular jar from the build? This will happen again in the future.

**Comment by Dimatert9** [comment]
Sorry, my fault. Do not check files size before download. Thanks for reply.

**Comment by sgdc3** [comment]
@ljacqu sure i just need to fix how we deploy stuff to the new repo

**Comment by ljacqu** [comment]
@sgdc3 Thank you :)
