### ISSUE TITLE
PacketAdapter class not found on reload

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1515]
Using latest build and doing /authme reload after unknown changes (I copied a user's config.yml) the following happened:

```
[09:12:30 WARN]: Unexpected exception while parsing console command "authme reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'authme' in plugin AuthMe v5.5.0-SNAPSHOT-bCUSTOM
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [spigot-server.jar:git-Spigot-f982156-22564a9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-server.jar:git-Spigot-f982156-22564a9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-server.jar:git-Spigot-f982156-22564a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-server.jar:git-Spigot-f982156-22564a9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-server.jar:git-Spigot-f982156-22564a9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_101]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_101]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_101]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-server.jar:git-Spigot-f982156-22564a9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at fr.xephi.authme.listener.protocollib.ProtocolLibService.reload(ProtocolLibService.java:110) ~[?:?]
```

**Comment by ljacqu** [comment]
This can be reproduced by not having ProtocolLib on the server but `ProtectInventoryBeforeLogIn: true` in the config and then changing it to false and reloading with /authme reload.

This is kind of a mindf/&#k to fix properly without breaking the restoration of inventories if inventory protection is legitimately turned off after having been on (including the possibility that ProtocolLib was disabled...). 

One quick fix would be to check with Utils#isClassLoaded whether such a class is loaded, but I'm also tempted to just close this as a wontfix since it's a marginal issue.

**Comment by Maxetto** [comment]
Why not just check if there's ProtocolLib and not activate Inventory Protection with a warning in Console?

**Comment by Maxetto** [comment]
Meh, might work too if we do this:
```
if (isEnabled == null || !isEnabled) {
    return;
    if (oldProtectInventory && !protectInvBeforeLogin) {
```

**Comment by games647** [comment]
It seems like inventoryPacketAdapter is just null in this case. So adding a != check would work too.

**Comment by sgdc3** [comment]
Ok, should be fixed, thank you @games647

**Comment by ljacqu** [comment]
I‘ll try it out, thanks @games647. My point is kinda I don‘t wanna mess up the already complex logic to handle this bordercase. So I‘ll give the not null check a try (I wonder if it isn‘t already too late since we‘re accessing a field whose type isn‘t available) and otherwise probably think of closing as it currently is. :)

**Comment by ljacqu** [comment]
OK I‘m too late to the party, I‘ll test it out. Thanka

**Comment by games647** [comment]
@ljacqu Sorry man. I originally wanted to exclude null-check line to wait for your response, because you assigned yourself to this ticket.

**Comment by ljacqu** [comment]
@games647 Nothing to be sorry about! I‘m on mobile so my „field of view“ was limited haha. I‘ll gladly test it this evening. I‘m happy you‘re taking care of the ProtocolLib stuff since you know it well.

**Comment by ljacqu** [comment]
I can no longer produce the issue, thank you!
