### ISSUE TITLE
Older SnakeYAML version used in Thermos 1.7.10

### ISSUE THREAD

**Issue by Eufranio** [AuthMe/AuthMeReloaded#1530]
### What behaviour is observed:
When my server is starting, AuthMe simply stops loading probably due to this error: http://prntscr.com/is2iuh
This only happened when my language was set to br. When setting it to en, it loaded just fine.

### What behaviour is expected:
The server would start as usual...

### Environment description
Single server under bungee

### AuthMe build number:
AuthMe 5.5.0 build 2030

**Comment by games647** [comment]
Could you post the AuthMe log file please?

**Comment by Eufranio** [comment]
I believe this is the latest log: https://hastebin.com/kiyaregova.vbs

**Comment by sgdc3** [comment]
@Eufranio Is it still happening?

**Comment by sgdc3** [comment]
@ljacqu any idea about this?

**Comment by ljacqu** [comment]
> Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.DumperOptions.setSplitLines(Z)V
	at fr.xephi.authme.message.updater.MigraterYamlFileResource.getSingleQuoteYaml(MigraterYamlFileResource.java:45)
	at fr.xephi.authme.libs.jalu.configme.resource.YamlFileResource.transformValue(YamlFileResource.java:214)
	at fr.xephi.authme.message.updater.MigraterYamlFileResource.toYaml(MigraterYamlFileResource.java:91)
	at fr.xephi.authme.message.updater.MigraterYamlFileResource.exportProperties(MigraterYamlFileResource.java:68)
	at fr.xephi.authme.libs.jalu.configme.SettingsManager.save(SettingsManager.java:143)
	at fr.xephi.authme.message.updater.MessageUpdater.migrateAndSave(MessageUpdater.java:71)
	at fr.xephi.authme.message.updater.MessageUpdater.migrateAndSave(MessageUpdater.java:48)
	at fr.xephi.authme.message.MessagesFileHandler.reloadInternal(MessagesFileHandler.java:28)
	at fr.xephi.authme.message.MessagesFileHandler.reload(MessagesFileHandler.java:21)

Oh my. 

What server version is this? I guess we don't shade the SnakeYAML instance and so relied on the one provided by Bukkit (etc.) and looks like whatever this server is running either has a newer or an older version of it.

**Comment by Eufranio** [comment]
I'm running Thermos, 1.7.10.

**Comment by sgdc3** [comment]
damn, we should start downloading libraries at runtime

**Comment by ljacqu** [comment]
AFAIK we have no more support for 1.7 and we've never heard of this again, so closing.
