### ISSUE TITLE
Async info error

### ISSUE THREAD

**Issue by Luky584** [AuthMe/AuthMeReloaded#1543]
ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:667) ~[server.jar:git-Paper-1370]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607) ~[server.jar:git-Paper-1370]
at fr.xephi.authme.service.BukkitService.dispatchConsoleCommand(BukkitService.java:327) ~[?:?]
at fr.xephi.authme.process.login.AsynchronousLogin.runCommandOtherAccounts(AsynchronousLogin.java:279) ~[?:?]
at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:241) ~[?:?]
at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:93) ~[?:?]
at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:54) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [server.jar:git-Paper-1370]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Paper-1370]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [server.jar:git-Paper-1370]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Thats all, i have this in console.

**Comment by sgdc3** [comment]
@Luky584 what's your authme version and build number? (/authme about)

**Comment by Luky584** [comment]
Sorry for late response: Version: AuthMeReloaded v5.4.0 (build: 1877)

**Comment by sgdc3** [comment]
Please try again with the latest dev build: https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
