### ISSUE TITLE
Constant error log in console

### ISSUE THREAD

**Issue by KevinM23** [AuthMe/AuthMeReloaded#1556]
### What behaviour is observed:
What happened?
Constantly seeing this event in console:

15.04 23:00:14 [Server] ERROR Could not pass event AsyncPlayerPreLoginEvent to AuthMe v5.4.0-b1877 15.04 23:00:14 [Server] INFO org.bukkit.event.EventException: null 15.04 23:00:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-9060bfa] 15.04 23:00:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-9060bfa] 15.04 23:00:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-9060bfa] 15.04 23:00:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-9060bfa]

### Steps/models to reproduce:
When players login to the server.

### Environment description
Spigot 1.12.2 server. SQLite database.

### AuthMe build number:
5.4.0 - Build: 1877

**Comment by KevinM23** [comment]
Hello,

I've updated, the problem persists.

Full error shown below:
`[16:51:54] [User Authenticator #17/ERROR]: Could not pass event AsyncPlayerPreLoginEvent to AuthMe v5.5.0-SNAPSHOT-b2049
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:271) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:187) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
Caused by: java.lang.NullPointerException: uuid
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_152]
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.hasPermission(VaultPermissionHook.java:120) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:132) ~[?:?]
	at fr.xephi.authme.permission.handlers.VaultHandler.hasPermissionOffline(VaultHandler.java:55) ~[?:?]
	at fr.xephi.authme.permission.PermissionsManager.hasPermissionOffline(PermissionsManager.java:278) ~[?:?]
	at fr.xephi.authme.listener.JoiningPlayer.lambda$fromName$0(JoiningPlayer.java:36) ~[?:?]
	at fr.xephi.authme.permission.PermissionsManager.hasPermission(PermissionsManager.java:236) ~[?:?]
	at fr.xephi.authme.listener.OnJoinVerifier.checkAntibot(OnJoinVerifier.java:72) ~[?:?]
	at fr.xephi.authme.listener.PlayerListener.runOnJoinChecks(PlayerListener.java:237) ~[?:?]
	at fr.xephi.authme.listener.PlayerListener.onAsyncPlayerPreLoginEvent(PlayerListener.java:269) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor866.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
	... 5 more`
