### ISSUE TITLE
Purge not working, console stuck.

### ISSUE THREAD

**Issue by jodo1** [AuthMe/AuthMeReloaded#1573]
### What behaviour is observed:
Purge not working, console totally stuck (server normally working). Problem happens after migration authme database to MySQL. Autopurge not working, purge command (/authme purge number) not working. Massive errors spam to log. /authme unregister nick working, but automatic purge not.

### Environment description
Standalone server, offline mode, Spigot 1.8.8, Build 201603010950, MySql database

### AuthMe build number:
AuthMe v5.4.0-b1877

### Error Log:
`[05:59:28] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.4.0-b1877
[05:59:44] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.4.0-b1877
[05:59:44] [Server thread/INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[05:59:44] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[05:59:45] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
[05:59:45] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Start completed.
[05:59:45] [Server thread/INFO]: [AuthMe] MySQL setup finished
[05:59:45] [Server thread/INFO]: [AuthMe] Hooked into PermissionsEx!
[05:59:45] [Server thread/INFO]: [AuthMe] Hooked successfully into Essentials
[05:59:45] [Server thread/INFO]: [AuthMe] Hooked successfully into Multiverse-Core
[05:59:45] [Server thread/INFO]: [AuthMe] [LICENSE] This product uses data from the GeoLite API created by MaxMind, available at http://www.maxmind.com
[05:59:45] [Server thread/INFO]: [AuthMe] Development builds are available on our jenkins, thanks to f14stelt.
[05:59:45] [Server thread/INFO]: [AuthMe] Do you want a good game server? Look at our sponsor GameHosting.it leader in Italy as Game Server Provider!
[05:59:45] [Server thread/INFO]: [AuthMe] AuthMe 5.4.0 build n.1877 correctly enabled!
[05:59:45] [Server thread/INFO]: [AuthMe] Automatically purging the database...
[05:59:45] [Server thread/INFO]: [AuthMe] Finished lookup of offlinePlayers. Begin looking purging player names only
[05:59:45] [Server thread/WARN]: [AuthMe] Task #87 for AuthMe v5.4.0-b1877 generated an exception
java.lang.IllegalArgumentException: Null or empty name passed! Name must not be empty
	at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:162) ~[?:?]
	at fr.xephi.authme.permission.handlers.PermissionsExHandler.hasPermissionOffline(PermissionsExHandler.java:48) ~[?:?]
	at fr.xephi.authme.permission.PermissionsManager.hasPermissionOffline(PermissionsManager.java:274) ~[?:?]
	at fr.xephi.authme.task.purge.PurgeTask.run(PurgeTask.java:88) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

### Configuration:
[https://gist.github.com/jodo1/e37f476190029a768d186d4cd2c3668e](url)

**Comment by ljacqu** [comment]
This is odd. Do  you have entry in your database where the name is empty?

**Comment by jodo1** [comment]
I do not know. Authme not allowed empty names.
