### ISSUE TITLE
AuthMe build #2141

### ISSUE THREAD

**Issue by LudnicaKiller** [AuthMe/AuthMeReloaded#1666]
I'm getting this error for AuthMeBridge when I install AuthMe build #2141 but there is no update for AuthMeBridge plugin:

> [03:25:29] [Server thread/WARN]: [AuthMeBridge] Task #261 for AuthMeBridge v1.6.2 generated an exception
> java.lang.NoClassDefFoundError: fr/xephi/authme/api/NewAPI
> 	at com.crylegend.authmebridge.AuthMeBridgeListener$1.run(AuthMeBridgeListener.java:33) ~[AuthMeBridge-1.6.2.jar:?]
> 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> Caused by: java.lang.ClassNotFoundException: fr.xephi.authme.api.NewAPI
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
> 	... 8 more

**Comment by LudnicaKiller** [comment]
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
