### ISSUE TITLE
NPE when getting permission groups from Vault, build 2101

### ISSUE THREAD

**Issue by LudnicaKiller** [AuthMe/AuthMeReloaded#1702]
### What behaviour is observed:
Error when starting the server

### Environment description
Spigot server, 1.8.8, http://prntscr.com/lql18o

### AuthMe build number:
http://prntscr.com/lql0uz

### Error Log:
https://pastebin.com/pDRHv6JW

**Comment by ljacqu** [comment]
Analysis: when the player joins we want to get the permission groups of the player but the vault API returns null instead of an expected empty list.

```
java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_151]
    at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[?:1.8.0_151]
    at java.util.Arrays.asList(Arrays.java:3800) ~[?:1.8.0_151]
    at fr.xephi.authme.permission.handlers.VaultHandler.getGroups(VaultHandler.java:79) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
    at fr.xephi.authme.permission.handlers.VaultHandler.getGroups(VaultHandler.java:19) ~[AuthMe-5.5.0-SNAPSHOT.jar:?]
```

VaultHandler.java:79 being the method body in the below code block:
```java
    @Override
    public List<String> getGroups(OfflinePlayer player) {
        return Arrays.asList(vaultProvider.getPlayerGroups(null, player));
    }
```

**Comment by ljacqu** [comment]
Hi @LudnicaKiller this should be fixed as of build nr. 2184. https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ 
May we ask you for a quick confirmation that it's also fixed on your side? Then we can close this issue or if something is open we can have a look at it.

**Comment by LudnicaKiller** [comment]
@ljacqu there is no errors for now. I think it's ok. 💃

**Comment by sgdc3** [comment]
Thank you ;)
