### ISSUE TITLE
Exception thrown when executing EssentialsX '/kickall'

### ISSUE THREAD

**Issue by lifehome** [AuthMe/AuthMeReloaded#1707]
### What behaviour is observed:
An exception has been thrown

### What behaviour is expected:
Nothing happened.

### Steps/models to reproduce:
Use `/kickall` provided by EssentialsX, to kick all players out.

### Plugin list:
AuthMeReloaded, EssentialsX

### Environment description
Paper 1.13.2 b474

### AuthMe build number:
b2181

### Error Log:
https://gist.github.com/lifehome/1a7efa28be16bf1891c3e423fdc9f82e

### Configuration:
default one would do, probably.

**Comment by lifehome** [comment]
It seems the problem escalated, every user login would throw this...
```
[20:27:15 INFO]: SteyrCamper[/10.147.17.149:12345] logged in with entity id 570 at ([lobby]-187.0, 73.0, -101.0)
[20:27:15 WARN]: [AuthMe] Plugin AuthMe v5.5.1-SNAPSHOT-b2181 generated an exception while executing task 186
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?]
        at fr.xephi.authme.libs.ch.jalu.datasourcecolumns.sqlimplementation.ResultSetValueRetriever.get(ResultSetValueRetriever.java:41) ~[?:?]
        at fr.xephi.authme.libs.ch.jalu.datasourcecolumns.sqlimplementation.SqlColumnsHandler.retrieve(SqlColumnsHandler.java:68) ~[?:?]
        at fr.xephi.authme.datasource.columnshandler.AuthMeColumnsHandler.retrieve(AuthMeColumnsHandler.java:148) ~[?:?]
        at fr.xephi.authme.datasource.AbstractSqlDataSource.hasSession(AbstractSqlDataSource.java:62) ~[?:?]
        at fr.xephi.authme.datasource.CacheDataSource.hasSession(CacheDataSource.java:220) ~[?:?]
        at fr.xephi.authme.service.SessionService.canResumeSession(SessionService.java:44) ~[?:?]
        at fr.xephi.authme.process.join.AsynchronousJoin.processJoin(AsynchronousJoin.java:120) ~[?:?]
        at fr.xephi.authme.process.Management.lambda$performJoin$6(Management.java:77) ~[?:?]
        at fr.xephi.authme.process.Management$$Lambda$2905.000000009DC74C40.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-476]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-476]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-476]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:825) [?:?]
[20:27:27 INFO]: [AuthMe] SteyrCamper logged in!
[20:27:28 INFO]: SteyrCamper joined the game
```

**Comment by sgdc3** [comment]
Strange :/ @ljacqu Any idea?

**Comment by ljacqu** [comment]
Looks like the code used maps that weren't thread-safe even though they needed to be. Replaced two maps with ConcurrentHashMaps. The error in the first post is probably fixed in the latest build; for the second one we need to wait for another build so that the new version of the data source columns lib is taken. :) But it's presumably fixed.
