### ISSUE TITLE
new authme  bypass methot

### ISSUE THREAD

**Issue by successed** [AuthMe/AuthMeReloaded#1757]
`[15:34:38] [User Authenticator #44/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@797d483a[id=9311d5c6-2b61-3095-86f4-f16589d95e12,name=EmRe3243,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.13.2.jar:git-Paper-525]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.13.2.jar:git-Paper-525]
    at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:37) ~[patched_1.13.2.jar:git-Paper-525]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.13.2.jar:git-Paper-525]
    at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:30) ~[patched_1.13.2.jar:git-Paper-525]
    at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:177) ~[patched_1.13.2.jar:git-Paper-525]
    at net.minecraft.server.v1_13_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:305) ~[patched_1.13.2.jar:git-Paper-525]
    at net.minecraft.server.v1_13_R2.LoginListener$1.run(LoginListener.java:205) ~[patched_1.13.2.jar:git-Paper-525]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

### What behaviour is observed:
What happened?
The player is sending different packets after logging in.

### What behaviour is expected:
What did you expect?
please fix this problem

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by sgdc3** [comment]
Please give us more details, also use pastebin to paste errors.

**Comment by games647** [comment]
@successed Is your server in online mode?

**Comment by successed** [comment]
> @successed Is your server in online mode?

no

**Comment by games647** [comment]
@successed What plugins do you have installed?
