### ISSUE TITLE
Problem and the server shuts down

### ISSUE THREAD

**Issue by PoloDarck** [AuthMe/AuthMeReloaded#1818]
### What behaviour is observed:
What happened?
The server enabled the plugin and then its shuts down
### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
 [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[23:30:40] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[23:30:40] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[23:30:40] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
This can be found by running `/authme version`
version of authme: 5.6.0 beta1

### Error Log:
[23:30:38] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta1-b2226
[23:30:39] [Server thread/INFO]: [AuthMe] Created column 'regdate' and set the current timestamp, 1558751439691, to all 0 rows
[23:30:40] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[23:30:40] [Server thread/INFO]: [AuthMe] Hooked into PermissionsEx!
[23:30:40] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[23:30:40] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[23:30:40] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[23:30:40] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!
[23:30:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:30:40] [Server thread/INFO]: Done (18.862s)! For help, type "help"
[23:30:40] [Server thread/INFO]: Stopping server
[23:30:40] [Server thread/INFO]: [EssentialsAntiBuild] Disabling EssentialsAntiBuild v2.16.1.125
[23:30:40] [Server thread/INFO]: [DeathMessages] Disabling DeathMessages v3.1.1
[23:30:40] [Server thread/INFO]: <<[ DeathMessages ]>>  [ Version ]=[ 3.1.1 ] [ Disabled! ]
[23:30:40] [Server thread/INFO]: [EssentialsGeoIP] Disabling EssentialsGeoIP v2.16.1.125
[23:30:40] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat v2.16.1.125
[23:30:40] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.16.1.125
[23:30:40] [Server thread/INFO]: [EssentialsProtect] Disabling EssentialsProtect v2.16.1.125
[23:30:40] [Server thread/INFO]: [Essentials] Disabling Essentials v2.16.1.125
[23:30:40] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.0.0-rc-2;7be00cc
[23:30:40] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[23:30:40] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[23:30:40] [Server thread/INFO]: Saving players
[23:30:41] [Server thread/INFO]: Saving worlds
[23:30:41] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[23:30:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[23:30:42] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
[23:30:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:30:43] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[23:30:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:30:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[23:30:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:30:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
>
C:\Users\admin1\Desktop\Server de minecraft>PAUSE
Presione una tecla para continuar . . .

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
Could you paste the error from your authme.log please? There should be a longer one

Also please try to update to the latest build, if you‘re running on 1.14 I think it should solve your issue :)

**Comment by PoloDarck** [comment]
[05-24 22:58:20]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[05-24 22:58:20]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[05-24 22:58:20]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:239)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:212)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:127)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:415)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:444)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:370)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:431)
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:243)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:739)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 16 more
Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.mail.EmailService'
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 32 more
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
	at fr.xephi.authme.mail.EmailService.<init>(EmailService.java:33)
	... 37 more

[05-24 22:58:20]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[05-24 22:58:20]: [INFO] AuthMe 5.6.0-beta1-b2226 disabled!
[05-24 23:29:30]: [INFO] SQLite Setup finished
[05-24 23:29:30]: [INFO] Hooked into PermissionsEx!
[05-24 23:29:30]: [INFO] Hooked successfully into Essentials
[05-24 23:29:30]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[05-24 23:29:30]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:239)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:212)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:127)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:415)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:444)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:370)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:431)
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:243)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:739)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 16 more
Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.mail.EmailService'
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 32 more
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
	at fr.xephi.authme.mail.EmailService.<init>(EmailService.java:33)
	... 37 more

[05-24 23:29:30]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[05-24 23:29:30]: [INFO] AuthMe 5.6.0-beta1-b2226 disabled!

**Comment by ljacqu** [comment]
Please download the latest build from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ This will fix your issue. (The AuthMe-5.6.0-SNAPSHOT.jar file)

**Comment by PoloDarck** [comment]
This problem fix this problem, thanks for passed me the lastest build and the next time i would like to see it in the spigot resources or bukkit not only in jenkins so it not difficult to find, i know that the plugin is in a beta version, but now you have to update it in the download of bukkit page, closing this issue.
