### ISSUE TITLE
crashes server / build (#2253)

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1825]
build (#2253) Min. 1.14.2
After some time, the problem begins:

```
02.06 22:43:46 [Server] User Authenticator #80/WARN Exception verifying leazy
02.06 22:43:46 [Server] INFO java.lang.IllegalStateException: AsyncPlayerPreLoginEvent cannot be triggered asynchronously from primary server thread.
02.06 22:43:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) ~[spigot.jar:git-Spigot-093165d-ba575a5]
02.06 22:43:46 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:266) ~[spigot.jar:git-Spigot-093165d-ba575a5]
02.06 22:43:46 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener$1.run(LoginListener.java:179) [spigot.jar:git-Spigot-093165d-ba575a5]
```

**Comment by Roper89** [comment]
@ljacqu Most likely this problem was caused by the plugin - [Infernal Mobs](https://www.spigotmc.org/resources/infernal-mobs.2156/)
After removing Infernal Mobs, while I do not observe problems.

**Comment by sgdc3** [comment]
There is no direct connection between this error and AuthMe.
