### ISSUE TITLE
Quit location not being saved

### ISSUE THREAD

**Issue by sixamscrew** [AuthMe/AuthMeReloaded#1839]
The players quit location isn't saving as well as the server crashes

Error Log:

[21:20:14] [Server thread/WARN]: [AuthMe] Task #434016 for AuthMe v5.6.0-SNAPSHOT-b2261 generated an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_212]
at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:204) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:144) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:91) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:105) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.Entity.setLocation(Entity.java:1272) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1105) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.PlayerConnection.teleport(PlayerConnection.java:1071) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:662) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:658) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:451) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at fr.xephi.authme.service.TeleportationService.lambda$performTeleportation$0(TeleportationService.java:185) ~[?:?]
at fr.xephi.authme.service.BukkitService.scheduleSyncTaskFromOptionallyAsyncTask(BukkitService.java:81) ~[?:?]
at fr.xephi.authme.service.TeleportationService.performTeleportation(TeleportationService.java:182) ~[?:?]
at fr.xephi.authme.service.TeleportationService.teleportBackFromSpawn(TeleportationService.java:166) ~[?:?]
at fr.xephi.authme.service.TeleportationService.teleportOnLogin(TeleportationService.java:143) ~[?:?]
at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:92) ~[?:?]
at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:52) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-df0eb25-efd8a2b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by ljacqu** [comment]
What's strange is that this is Bukkit/Minecraft code immediately causing this error. Please make sure you're running the latest version and that your world doesn't have some issue. Does everything else function normally?

**Comment by sixamscrew** [comment]
Hello, I updated AuthMe but I figured out that Multiverse core is the issue. This is not AuthMe fault. Thank you for the help.

**Comment by legg3nda2** [comment]
> Hello, I updated AuthMe but I figured out that Multiverse core is the issue. This is not AuthMe fault. Thank you for the help.

Can you tell me what is the problem with multiverse core? Cause i have the same problem.
