### ISSUE TITLE
1.14.4 server turns off ,when I put AuthMe plugin

### ISSUE THREAD

**Issue by Dzgs** [AuthMe/AuthMeReloaded#1918]
### What behaviour is observed:
Trying to turn on the server with AuthMe ,but the server turns off.

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
![image](https://user-images.githubusercontent.com/52612280/65982491-20e1dd80-e484-11e9-8795-3331de141aeb.png)

### Environment description
Standalone server ,PaperSpigot 1.14.4

### AuthMe build number:
AuthMe 5.6.0-SNAPSHOT

### Error Log:
[19:42:37] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2314
[19:42:37] [Server thread/WARN]: No space left on device
[19:42:37] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [UnsatisfiedLinkError]: org.sqlite.core.NativeDB._open_utf8([BI)V
[19:42:37] [Server thread/WARN]: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
[19:42:37] [Server thread/WARN]: at org.sqlite.core.NativeDB._open_utf8(Native Method)
[19:42:37] [Server thread/WARN]: at org.sqlite.core.NativeDB._open(NativeDB.java:78)
[19:42:37] [Server thread/WARN]: at org.sqlite.core.DB.open(DB.java:195)
[19:42:37] [Server thread/WARN]: at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
[19:42:37] [Server thread/WARN]: at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
[19:42:37] [Server thread/WARN]: at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
[19:42:37] [Server thread/WARN]: at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
[19:42:37] [Server thread/WARN]: at org.sqlite.JDBC.createConnection(JDBC.java:115)
[19:42:37] [Server thread/WARN]: at org.sqlite.JDBC.connect(JDBC.java:90)
[19:42:37] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:664)
[19:42:37] [Server thread/WARN]: at java.sql.DriverManager.getConnection(DriverManager.java:270)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.datasource.SQLite.connect(SQLite.java:91)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.datasource.SQLite.<init>(SQLite.java:58)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:73)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:251)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.AuthMe.initialize(AuthMe.java:227)
[19:42:37] [Server thread/WARN]: at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:146)
[19:42:37] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:42:37] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[19:42:37] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[19:42:37] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[19:42:37] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[19:42:37] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[19:42:37] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[19:42:37] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[19:42:37] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[19:42:37] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[19:42:37] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[19:42:37] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT-b2314 disabled!

### Configuration:
Config is Default

**Comment by vini2003** [comment]
Can confirm, same issue on Paper 225.

**Comment by sgdc3** [comment]
`[19:42:37] [Server thread/WARN]: No space left on device`

Wtf, this is shown when your hdd is full...
