### ISSUE TITLE
crash on 1.15

### ISSUE THREAD

**Issue by Mitsu13Ion** [AuthMe/AuthMeReloaded#1961]
### What behaviour is observed:
What happened?
crash
### What behaviour is expected:
What did you expect?
a start
### Steps/models to reproduce:
The actions that cause the issue
paper-5 (1.15) 
### Plugin list:
This can be found by running `/pl`
Only authme and skinsrestorer
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone server mysql
### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
[19:08:00] [Server thread/INFO]: [AuthMe] [LICENSE] This product includes GeoLite2 data created by MaxMind, available at https://www.maxmind.com
[19:08:01] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[19:08:01] [Server thread/WARN]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:247)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
[19:08:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:08:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[19:08:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[19:08:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[19:08:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[19:08:01] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481)
[19:08:01] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[19:08:01] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[19:08:01] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:08:01] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[19:08:01] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:08:01] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:01] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:01] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
[19:08:01] [Server thread/WARN]: 	... 16 more
[19:08:01] [Server thread/WARN]: Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.listener.protocollib.ProtocolLibService'
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
[19:08:01] [Server thread/WARN]: 	... 21 more
[19:08:01] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[19:08:01] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:08:01] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:01] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:01] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
[19:08:01] [Server thread/WARN]: 	... 38 more
[19:08:01] [Server thread/WARN]: Caused by: FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:259)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.concurrency.PacketTypeSet.addType(PacketTypeSet.java:35)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.addPacketHandler(ProtocolInjector.java:385)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:624)
[19:08:01] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:390)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.InventoryPacketAdapter.register(InventoryPacketAdapter.java:78)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.ProtocolLibService.setup(ProtocolLibService.java:70)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.ProtocolLibService.reload(ProtocolLibService.java:133)
[19:08:01] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.ProtocolLibService.<init>(ProtocolLibService.java:44)
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
base config.yml

**Comment by krusic22** [comment]
Outdated version of AuthMe.
Use the latest version from Jenkins/Build CI.

**Comment by Mitsu13Ion** [comment]
It's 5.6.0-snapshot 2343

**Comment by krusic22** [comment]
Then it could be outdated ProtocolLib.

**Comment by Mitsu13Ion** [comment]
It's that, Thanks u

**Comment by celciusjj** [comment]
@Mitsu13Ion working for you?
