### ISSUE TITLE
shutting down

### ISSUE THREAD

**Issue by rogerxavier93** [AuthMe/AuthMeReloaded#1964]
getting this error on paper 1.15

15.12 23:28:28 [Server] INFO [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
15.12 23:28:28 [Server] WARN [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
15.12 23:28:28 [Server] WARN [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Start completed.
15.12 23:28:28 [Server] INFO [AuthMe] MySQL setup finished
15.12 23:28:28 [Server] INFO [AuthMe] Hooked into Vault!
15.12 23:28:28 [Server] INFO [AuthMe] Hooked successfully into Essentials
15.12 23:28:28 [Server] INFO [AuthMe] Hooked successfully into Multiverse-Core
15.12 23:28:28 [Server] INFO [AuthMe] [LICENSE] This product includes GeoLite2 data created by MaxMind, available at https://www.maxmind.com
15.12 23:28:28 [Server] WARN [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
15.12 23:28:28 [Server] WARN [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
15.12 23:28:28 [Server] INFO [AuthMe] Waiting for 0 tasks to finish
15.12 23:28:28 [Server] WARN [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown initiated...
15.12 23:28:28 [Server] WARN [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown completed.
15.12 23:28:28 [Server] INFO [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!

**Comment by ljacqu** [comment]
Please post the full error in your authme.lig

**Comment by Lice2** [comment]
hi, i have the same problem under minecraft v1.15.1
here is the Authme.log

[12-20 13:09:32]: [INFO] SQLite Setup finished
[12-20 13:09:32]: [INFO] Hooked into Vault!
[12-20 13:09:32]: [INFO] Hooked successfully into Essentials
[12-20 13:09:32]: [INFO] Hooked successfully into Multiverse-Core
[12-20 13:09:32]: [INFO] [LICENSE] This product includes GeoLite2 data created by MaxMind, available at https://www.maxmind.com
[12-20 13:09:33]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[12-20 13:09:33]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:247)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 16 more
Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.listener.protocollib.ProtocolLibService'
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 36 more
Caused by: FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216)
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57)
	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:259)
	at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82)
	at com.comphenix.protocol.concurrency.PacketTypeSet.addType(PacketTypeSet.java:35)
	at com.comphenix.protocol.injector.spigot.AbstractPacketInjector.addPacketHandler(AbstractPacketInjector.java:30)
	at com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:634)
	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:402)
	at fr.xephi.authme.listener.protocollib.TabCompletePacketAdapter.register(TabCompletePacketAdapter.java:38)
	at fr.xephi.authme.listener.protocollib.ProtocolLibService.setup(ProtocolLibService.java:80)
	at fr.xephi.authme.listener.protocollib.ProtocolLibService.reload(ProtocolLibService.java:133)
	at fr.xephi.authme.listener.protocollib.ProtocolLibService.<init>(ProtocolLibService.java:44)
	... 41 more

[12-20 13:09:33]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2347 disabled!

**Comment by ljacqu** [comment]
Can you try to update your protocolLib version please? It‘s a call we make to them that fails. 
Temp fix is disabling tab completion (I‘m not sure it‘s configurable and I‘m on mobile, sorry 😅

**Comment by Lice2** [comment]
Excellent ! Thanks now it works!
