### ISSUE TITLE
Authe me Mail bug

### ISSUE THREAD

**Issue by PlaxCraft** [AuthMe/AuthMeReloaded#1988]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
AuthMeReloaded 5.6.0-beta1
### What behaviour is observed:
What happened?
[WARN] Failed to send a mail to [rikoko2000@gmail.com]: [EmailException]: Sending the email to the following server failed : smtp-relay.sendinblue.com:587

### What behaviour is expected:
What did you expect?
nothing
### Steps/models to reproduce:
The actions that cause the issue
[01-16 05:29:50]: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp-relay.sendinblue.com:587
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at fr.xephi.authme.mail.SendMailSsl.sendEmail(SendMailSsl.java:103)
	at fr.xephi.authme.mail.EmailService.sendRecoveryCode(EmailService.java:129)
	at fr.xephi.authme.service.PasswordRecoveryService.createAndSendRecoveryCode(PasswordRecoveryService.java:73)
	at fr.xephi.authme.command.executable.email.RecoverEmailCommand.lambda$runCommand$0(RecoverEmailCommand.java:76)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.mail.AuthenticationFailedException: 530 Invalid username or password

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 11 more
### Plugin list:
This can be found by running `/pl`
yes
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
yes
### AuthMe build number:
This can be found by running `/authme version`
new version 
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
As the error says, looks like you provided the wrong name (i.e. email) or password for the account you configured to send emails from

**Comment by PlaxCraft** [comment]
hmm

**Comment by PlaxCraft** [comment]
what you mean by that

**Comment by PlaxCraft** [comment]
Email:
    # Email SMTP server host
    mailSMTP: smtp-relay.sendinblue.com
    # Email SMTP server port
    mailPort: 587
    # Only affects port 25: enable TLS/STARTTLS?
    useTls: false
    # Email account which sends the mails
    mailAccount: 'mc.plexcrafts@gmail.com'
    # Email account password
    mailPassword: '4355789aaAA'
    # Email address, fill when mailAccount is not the email address of the account
    mailAddress: ''
    # Custom sender name, replacing the mailAccount name in the email
    mailSenderName: ''
    # Recovery password length
    RecoveryPasswordLength: 8
    # Mail Subject
    mailSubject: Your new AuthMe password
    # Like maxRegPerIP but with email
    maxRegPerEmail: 1
    # Recall players to add an email?
    recallPlayers: false
    # Delay in minute for the recall scheduler
    delayRecall: 5
    # Blacklist these domains for emails
    emailBlacklisted: 
    - 10minutemail.com
    # Whitelist ONLY these domains for emails
    emailWhitelisted: []
    # Send the new password drawn in an image?
    generateImage: false
    # The OAuth2 token
    emailOauth2Token: ''

**Comment by ljacqu** [comment]
I mean you‘re configuring to send emails from an @gmail address but you set the mailSMTP value to not be gmail‘s server— they need to be in sync. It needs to be gmail‘s smtp server

**Comment by PlaxCraft** [comment]
How to find this

**Comment by ljacqu** [comment]
I see a Google search with "gmail's stmp server" delivers some nice tutorials on what values need to be provided. Looks like the smtp server is smtp.gmail.com.
