### ISSUE TITLE
GeoIP error

### ISSUE THREAD

**Issue by Gerolfing** [AuthMe/AuthMeReloaded#2026]
In config file I have provided all actual info for GeoIP functionality (clientId&LicenceKey)

But when server starts plugin can't update GeoIp databases and I get this error:
```
[14:02:42] [Craft Scheduler Thread - 9/WARN]: [AuthMe] Plugin AuthMe v5.6.0-SNAPSHOT-b2379 generated an exception while executing task 34
java.lang.NullPointerException: text
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_231]
	at java.time.format.DateTimeFormatter.parse(Unknown Source) ~[?:1.8.0_231]
	at fr.xephi.authme.service.GeoIpService.downloadDatabaseArchive(GeoIpService.java:216) ~[?:?]
	at fr.xephi.authme.service.GeoIpService.downloadDatabaseArchive(GeoIpService.java:235) ~[?:?]
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:141) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-173]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-173]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-173]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```
Maybe I did something wrong? I created account and get licence at MaxMind for free GeoLite2 Database, maybe authme need other?

**Comment by krusic22** [comment]
#1979

**Comment by Gerolfing** [comment]
> #1979

Excuse me, I didn't quite get it, so for now it's not working even with private licence key?

**Comment by krusic22** [comment]
You need an free API key.
Download the latest AuthMe from the build CI, run it once (so that the config gets updated), follow the guide here: https://essentialsx.cf/wiki/GeoIP.html and put the API info into the AuthMe config.

**Comment by Gerolfing** [comment]
> You need an free API key.
> Download the latest AuthMe from the build CI, run it once (so that the config gets updated), follow the guide here: https://essentialsx.cf/wiki/GeoIP.html and put the API info into the AuthMe config.

That's exactly what I did

**Comment by Gerolfing** [comment]
My bad, I filled in email in clienid, while there must be just numbers form id. Problem solved
