### ISSUE TITLE
Server shutting down on Paper 1.15.2

### ISSUE THREAD

**Issue by partytoni** [AuthMe/AuthMeReloaded#2057]
Hello,
i am using your plugin on paper 1.15.2 on a raspberry pi.
I tried both snapshot version and beta version of the plugin but they are all giving me this error and shutting down the server:

`[04-01 12:14:42]: [INFO] Created column 'regdate' and set the current timestamp, 1585736082630, to all 0 rows
[04-01 12:14:43]: [INFO] SQLite Setup finished
[04-01 12:14:44]: [INFO] No supported permissions system found! Permissions are disabled!
[04-01 12:14:45]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[04-01 12:14:45]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
        at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
        at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
        at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:250)
        at fr.xephi.authme.AuthMe.initialize(AuthMe.java:223)
        at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:133)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
        ... 16 more
Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.mail.EmailService'
        at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
        at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
        at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
        at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
        at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
        ... 21 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
        ... 36 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getServerName()'
        at fr.xephi.authme.mail.EmailService.<init>(EmailService.java:33)
        ... 41 more

[04-01 12:14:45]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[04-01 12:14:46]: [INFO] AuthMe 5.5.0-SNAPSHOT-b2175 disabled!`

can you help me?

**Comment by ljacqu** [comment]
Please grab a newer build from our Jenkins at https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/ This is an issue we fixed a while ago that came up with Minecraft 1.15
