### ISSUE TITLE
Error loading in a scratch spigot server

### ISSUE THREAD

**Issue by andreileonsalas** [AuthMe/AuthMeReloaded#2133]
### What behaviour is observed:
What happened?
created the spigot server, loaded, put the plugin, it no longer loads
### What behaviour is expected:
What did you expect?
to loads the server
### Steps/models to reproduce:
The actions that cause the issue
putting the plugin in the plugin folder
### Plugin list:
This can be found by running `/pl`
server does not start
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
spigot server only and this plugin
### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
[21:01:15] [Server thread/INFO]: Time elapsed: 1075 ms
[21:01:15] [Server thread/INFO]: [Essentials] Enabling Essentials v2.17.2.123
[21:01:15] [Server thread/INFO]: Attempting to convert old kits in config.yml to new kits.yml
[21:01:15] [Server thread/INFO]: No kits found to migrate.
[21:01:15] [Server thread/INFO]: [Essentials] Starting Essentials ban format conversion
[21:01:15] [Server thread/INFO]: [Essentials] Starting usermap repair
[21:01:15] [Server thread/WARN]: [Essentials] Missing userdata folder, aborting
[21:01:15] [Server thread/INFO]: Attempting to migrate ignore list to UUIDs
[21:01:16] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[21:01:16] [Server thread/INFO]: [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
[21:01:16] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[21:01:16] [Server thread/INFO]: Loaded 21019 items from items.json.
[21:01:16] [Server thread/INFO]: Using locale en_US
[21:01:16] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[21:01:16] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[21:01:16] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[21:01:16] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-SNAPSHOT-b2405
[21:01:16] [Server thread/WARN]: Failed to load native library:sqlite-3.30.1-845a04c6-3cb9-4fc4-b89e-cfbc5a0ae6f0-libsqlitejdbc.so. osinfo: Linux/x86_64
[21:01:16] [Server thread/WARN]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.30.1-845a04c6-3cb9-4fc4-b89e-cfbc5a0ae6f0-libsqlitejdbc.so: /tmp/sqlite-3.30.1-845a04c6-3cb9-4fc4-b89e-cfbc5a0ae6f0-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted
[21:01:16] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [UnsatisfiedLinkError]: org.sqlite.core.NativeDB._open_utf8([BI)V
[21:01:16] [Server thread/WARN]: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
[21:01:16] [Server thread/WARN]:        at org.sqlite.core.NativeDB._open_utf8(Native Method)
[21:01:16] [Server thread/WARN]:        at org.sqlite.core.NativeDB._open(NativeDB.java:78)
[21:01:16] [Server thread/WARN]:        at org.sqlite.core.DB.open(DB.java:195)
[21:01:16] [Server thread/WARN]:        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243)
[21:01:16] [Server thread/WARN]:        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61)
[21:01:16] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
[21:01:16] [Server thread/WARN]:        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
[21:01:16] [Server thread/WARN]:        at org.sqlite.JDBC.createConnection(JDBC.java:115)
[21:01:16] [Server thread/WARN]:        at org.sqlite.JDBC.connect(JDBC.java:90)
[21:01:16] [Server thread/WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:664)
[21:01:16] [Server thread/WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:270)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.datasource.SQLite.connect(SQLite.java:91)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.datasource.SQLite.<init>(SQLite.java:58)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:73)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
[21:01:16] [Server thread/WARN]:        at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
[21:01:16] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:01:16] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[21:01:16] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[21:01:16] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
[21:01:16] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
[21:01:16] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[21:01:16] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
[21:01:16] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[21:01:16] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:01:16] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[21:01:16] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[21:01:16] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT-b2405 disabled!
[21:01:17] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:01:17] [Server thread/INFO]: Done (21.568s)! For help, type "help"
[21:01:17] [Server thread/INFO]: Stopping server
[21:01:17] [Server thread/INFO]: [Essentials] Disabling Essentials v2.17.2.123
[21:01:17] [Server thread/INFO]: Saving players
[21:01:17] [Server thread/INFO]: Saving worlds
[21:01:17] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[21:01:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:01:18] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
[21:01:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:01:18] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[21:01:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:01:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:01:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:01:18] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by devomaa** [comment]
> [21:01:16] [Server thread/WARN]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.30.1-845a04c6-3cb9-4fc4-b89e-cfbc5a0ae6f0-libsqlitejdbc.so: /tmp/sqlite-3.30.1-845a04c6-3cb9-4fc4-b89e-cfbc5a0ae6f0-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted


Try a user that is permitted to access `/tmp/sqlite-3.30.1-..`

**Comment by Ironman2M** [comment]
And also link it with mysql database

**Comment by sgdc3** [comment]
@andreileonsalas as @devomaa this is an user permission issue
