### ISSUE TITLE
stopping server sql problem

### ISSUE THREAD

**Issue by Misick** [AuthMe/AuthMeReloaded#2135]
[23:24:39 INFO]: [WorldGuard] Loading region data...
[23:24:39 INFO]: [AuthMe] Enabling AuthMe v5.4.0-b1877
[23:24:39 INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[23:24:39 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[23:24:40 WARN]: [Server thread] ERROR fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Exception during pool initialization.
[23:24:40 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'authme'
[23:24:40 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:24:40 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:24:40 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:24:40 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:24:40 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[23:24:40 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[23:24:40 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[23:24:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[23:24:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[23:24:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
[23:24:40 WARN]:        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
[23:24:40 WARN]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
[23:24:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
[23:24:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2230)
[23:24:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2025)
[23:24:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
[23:24:40 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[23:24:40 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:24:40 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:24:40 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:24:40 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:24:40 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[23:24:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[23:24:40 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
[23:24:40 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
[23:24:40 WARN]:        at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
[23:24:40 WARN]:        at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
[23:24:40 WARN]:        at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
[23:24:40 WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
[23:24:40 WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
[23:24:40 WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
[23:24:40 WARN]:        at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
[23:24:40 WARN]:        at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
[23:24:40 WARN]:        at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
[23:24:40 WARN]:        at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
[23:24:40 WARN]:        at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
[23:24:40 WARN]:        at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
[23:24:40 WARN]:        at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
[23:24:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[23:24:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[23:24:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[23:24:40 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[23:24:40 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[23:24:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[23:24:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[23:24:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[23:24:40 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[23:24:40 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[23:24:40 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:24:40 WARN]: [AuthMe] Can't initialize the MySQL database: [MySQLSyntaxErrorException]: Unknown database 'authme'
[23:24:40 WARN]: [AuthMe] Please check your database settings in the config.yml file!
[23:24:40 WARN]: [AuthMe] Could not create data source: [MySQLSyntaxErrorException]: Unknown database 'authme'
[23:24:40 WARN]: [AuthMe] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[23:24:40 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[23:24:40 INFO]: [AuthMe] Waiting for 0 tasks to finish
[23:24:40 INFO]: [AuthMe] AuthMe 5.4.0-b1877 disabled!
[23:24:40 INFO]: [TAB] Enabling TAB v2.7.6
[23:24:40 INFO]: [TAB] Server version: 1.13.2 (v1_13_R2)
[23:24:40 INFO]: [TAB] File plugins\TAB\errors.txt exists and is not empty. Please take a look at the errors and try to correct them. You can also join our discord for assistance. After you resolve them, delete the file.
[23:24:41 INFO]: [TAB] There was 1 startup warning.
[23:24:41 INFO]: [TAB] Enabled in 35ms
[23:24:41 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:24:41 INFO]: [TAB] Version 2.7.7 is out! Your version: 2.7.6
[23:24:41 INFO]: [TAB] Get the update at https://www.spigotmc.org/resources/57806/
[23:24:41 INFO]: Done (8.533s)! For help, type "help"
[23:24:41 INFO]: Stopping server
[23:24:41 INFO]: [TAB] Disabling TAB v2.7.6
[23:24:41 INFO]: [TAB] Disabled in 1ms
[23:24:41 INFO]: [WorldGuard] Disabling WorldGuard v7.0.0;02b731f
[23:24:41 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[23:24:41 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.0.0-b766
[23:24:41 INFO]: [Essentials] Disabling Essentials v2.17.2.0
[23:24:41 INFO]: [ViaVersion] Disabling ViaVersion v3.0.0-SNAPSHOT
[23:24:41 INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[23:24:41 INFO]: [WorldEdit] Disabling WorldEdit v7.1.0;8e55131
[23:24:41 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[23:24:41 INFO]: [SkinsRestorer] Disabling SkinsRestorer v13.7.9
[23:24:41 INFO]: [LuckPerms] Disabling LuckPerms v5.1.55
[23:24:41 INFO]: [LuckPerms] Starting shutdown process...
[23:24:41 INFO]: [LuckPerms] Closing messaging service...
[23:24:41 INFO]: [LuckPerms] Closing storage...
[23:24:41 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Shutdown initiated...
[23:24:41 WARN]: [Server thread] INFO me.lucko.luckperms.lib.hikari.HikariDataSource - luckperms-hikari - Shutdown completed.
[23:24:41 INFO]: [LuckPerms] Goodbye!
[23:24:41 INFO]: Saving players
[23:24:41 INFO]: Saving worlds
[23:24:41 INFO]: Saving chunks for level 'Server'/minecraft:overworld
[23:24:41 INFO]: Saving chunks for level 'Server_nether'/minecraft:the_nether
[23:24:41 INFO]: Saving chunks for level 'Server_the_end'/minecraft:the_end
>Press any key to continue . . .

**Comment by Misick** [comment]
solved
