### ISSUE TITLE
Newest LuckPerms version unsupported

### ISSUE THREAD

**Issue by SkepsonSk** [AuthMe/AuthMeReloaded#2141]
### What behaviour is observed:
AuthMe is disabling itself or the server.

### What behaviour is expected:
I expected it to link to the newest LuckPerms (5.1.26) and run

### Steps/models to reproduce:
Wrong main classpath to newest LuckPerms

### Plugin list:
Prefer not to send

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
AuthMe 5.6.0-beta1

### Error Log:
[06-28 01:26:59]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-28 01:26:59]: [INFO] MySQL setup finished
[06-28 01:26:59]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@4debbded
[06-28 01:26:59]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@4debbded
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:76)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.postProcess(PostConstructMethodInvoker.java:27)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:271)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:239)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:212)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:127)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:73)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
	at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:38)
	at fr.xephi.authme.permission.PermissionsManager.createPermissionHandler(PermissionsManager.java:135)
	at fr.xephi.authme.permission.PermissionsManager.setup(PermissionsManager.java:92)
	... 28 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 31 more

**Comment by ljacqu** [comment]
Please take a newer version from our Jenkins at https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/
