### ISSUE TITLE
Authme Bug

### ISSUE THREAD

**Issue by AlinMihai96** [AuthMe/AuthMeReloaded#2146]
[Server thread/WARN]: Unexpected exception while parsing console command "authme"
org.bukkit.command.CommandException: Cannot execute command 'authme' in plugin AuthMe v5.4.0-b1877 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:696) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:436) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:400) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
>Unexpected exception while parsing console command "authme"

**Comment by ljacqu** [comment]
>  plugin is disabled.

So was there an error when it started? Or was this during shutting down? Why didn't you fill in the issue template?

**Comment by AlinMihai96** [comment]
Error is on start.

[09:17:34] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.4.0-b1877
[09:17:34] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[09:17:34] [Server thread/INFO]: [AuthMe] Hooked into Vault!
[09:17:34] [Thread-63/WARN]: [AuthMe] Could not download GeoLiteAPI database [UnknownHostException]: geolite.maxmind.com
[09:17:34] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[09:17:34] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[09:17:34] [Server thread/INFO]: [AuthMe] AuthMe 5.4.0-b1877 disabled!

**Comment by ljacqu** [comment]
You‘re using a really old version. Please update to a newer build https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/
