### ISSUE TITLE
Authme not working

### ISSUE THREAD

**Issue by AaronmolaGames** [AuthMe/AuthMeReloaded#2253]
### Error Log: 
[15:14:19 WARN]: Plugin AuthMe v5.4.0-b1877 generated an exception while executing task 479
java.lang.NullPointerException: null
	at fr.xephi.authme.ConsoleLogger.writeLog(ConsoleLogger.java:240) ~[?:?]
	at fr.xephi.authme.ConsoleLogger.warning(ConsoleLogger.java:93) ~[?:?]
	at fr.xephi.authme.ConsoleLogger.logException(ConsoleLogger.java:104) ~[?:?]
	at fr.xephi.authme.datasource.SqlDataSourceUtils.logSqlException(SqlDataSourceUtils.java:23) ~[?:?]
	at fr.xephi.authme.datasource.SQLite.getAccountsRegistered(SQLite.java:577) ~[?:?]
	at fr.xephi.authme.datasource.CacheDataSource.getAccountsRegistered(CacheDataSource.java:234) ~[?:?]
	at fr.xephi.authme.initialization.DataSourceProvider.lambda$checkDataSourceSize$0(DataSourceProvider.java:94) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-351]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-351]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by krusic22** [comment]
You should at least use the latest AuthMe version before reporting issues.

**Comment by AaronmolaGames** [comment]
i did and the error still appears

**Comment by ljacqu** [comment]
Too lazy to open AuthMe in my IDE right now but could genuinely be a bug, looking at the stacktrace. Though interesting to note that your database has some issue:

> at fr.xephi.authme.datasource.SqlDataSourceUtils.logSqlException(SqlDataSourceUtils.java:23) ~[?:?]
> at fr.xephi.authme.datasource.SQLite.getAccountsRegistered(SQLite.java:577) ~[?:?]

We don't know what since it then causes a logging issue but something goes wrong when it reads your DB
