### ISSUE TITLE
[InjectorReflectorException]: Could not invoke constructor of class 'class fr.exphi.authme.command.CommandHandler'

### ISSUE THREAD

**Issue by Maks1116** [AuthMe/AuthMeReloaded#2312]
### What behaviour is observed:
What happened?
authme crashes with error: [InjectorReflectorException]: Could not invoke constructor of class 'class fr.exphi.authme.command.CommandHandler'

### What behaviour is expected:
What did you expect?
I expected it to not throw this error and to work

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`
https://imgur.com/a/qFxvE0j
https://imgur.com/a/hz9ufHQ
https://imgur.com/a/quvQJXl
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord network, MySQL
### AuthMe build number:
This can be found by running `/authme version`
Plugin isn't loading, so I cannot check it, but I downloaded it hour ago
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
https://pastebin.com/Ri0SxRBS
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/SYS1unqT

**Comment by ljacqu** [comment]
Sorry if I‘m being done (viewing this on a cellphone) but on what line in the log is the error that you reference? We absolutely need to have the full stacktrace to your error to determine the cause

**Comment by Maks1116** [comment]
It is in line 1190

**Comment by ljacqu** [comment]
Thanks. Do you have the error as shown in authme.log? We need to have more information about the error

**Comment by Maks1116** [comment]
Yes, I have something here. There's also another crash but it was error with permission plugin and I fixed it.
```
[03-01 14:52:11]: [INFO] Created column 'regdate' and set the current timestamp, 1614606731411, to all 0 rows
[03-01 14:52:11]: [INFO] SQLite Setup finished
[03-01 14:52:11]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@18d0d889
[03-01 14:52:11]: fr.xephi.authme.libs.jalu.injector.exceptions.InjectorReflectionException: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@18d0d889
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:76)
	at fr.xephi.authme.libs.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:25)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:248)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:73)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
	at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:37)
	at fr.xephi.authme.permission.PermissionsManager.createPermissionHandler(PermissionsManager.java:137)
	at fr.xephi.authme.permission.PermissionsManager.setup(PermissionsManager.java:96)
	... 28 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 31 more

[03-01 14:52:11]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[03-01 14:52:11]: [INFO] AuthMe 5.4.0-b1877 disabled!
[03-31 09:26:19]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-31 09:26:21]: [INFO] Created column 'regdate' and set the current timestamp, 1617175581176, to all 0 rows
[03-31 09:26:21]: [INFO] MySQL setup finished
[03-31 09:26:22]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@2d28628b
[03-31 09:26:22]: fr.xephi.authme.libs.jalu.injector.exceptions.InjectorReflectionException: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@2d28628b
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:76)
	at fr.xephi.authme.libs.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:25)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:248)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:73)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
	at fr.xephi.authme.permission.handlers.LuckPermsHandler.<init>(LuckPermsHandler.java:37)
	at fr.xephi.authme.permission.PermissionsManager.createPermissionHandler(PermissionsManager.java:137)
	at fr.xephi.authme.permission.PermissionsManager.setup(PermissionsManager.java:96)
	... 28 more
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 31 more

[03-31 09:26:22]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[03-31 09:26:22]: [INFO] AuthMe 5.4.0-b1877 disabled!
[03-31 09:41:23]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[03-31 09:41:24]: [INFO] MySQL setup finished
[03-31 09:41:24]: [INFO] Hooked into LuckPerms!
[03-31 09:41:24]: [INFO] Hooked successfully into Essentials
[03-31 09:41:24]: [INFO] Hooked successfully into Multiverse-Core
[03-31 09:41:24]: [WARN] Could not download GeoLiteAPI database [UnknownHostException]: geolite.maxmind.com
[03-31 09:41:24]: java.net.UnknownHostException: geolite.maxmind.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at fr.xephi.authme.service.GeoIpService$1.run(GeoIpService.java:93)
	at java.lang.Thread.run(Thread.java:748)

[03-31 09:41:24]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[03-31 09:41:24]: fr.xephi.authme.libs.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:62)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:248)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 16 more
Caused by: fr.xephi.authme.libs.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.mail.EmailService'
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
	at fr.xephi.authme.libs.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:62)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177)
	at fr.xephi.authme.libs.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:82)
	at fr.xephi.authme.initialization.factory.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:41)
	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at fr.xephi.authme.libs.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
	... 39 more
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
	at fr.xephi.authme.mail.EmailService.<init>(EmailService.java:33)
	... 44 more

[03-31 09:41:24]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[03-31 09:41:24]: [INFO] AuthMe 5.4.0-b1877 disabled!

```

**Comment by ljacqu** [comment]
Thanks

> java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
>  AuthMe 5.4.0-b1877

This is caused by a change that was introduced in Bukkit 1.14. We fixed it a while back so if you grab a newer build you should be good to go:  https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/

**Comment by Maks1116** [comment]
Thank you for help!

**Comment by Maks1116** [comment]
So I checked if it works and even in latest build error still occurs.

**Comment by ljacqu** [comment]
What‘s the error this time? If it‘s still the serverName thing I highlighted it‘s still the old JAR for some reason

**Comment by Maks1116** [comment]
It is same error even with latest dev builds.

**Comment by sgdc3** [comment]
@Maks1116 then you didn't upload the latest jar, please double check.

**Comment by Maks1116** [comment]
I double checked and I still have same problem

**Comment by Maks1116** [comment]
Ok it works, my server is cursed

**Comment by Maks1116** [comment]
And now it works only in half of my servers
```
[18:23:03] [Server thread/INFO]: [AuthMe] Essentials spawn file not found: '/var/lib/pufferpanel/servers/33f855e1/plugins/Essentials/spawn.yml'
[18:23:05] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[18:23:05] [Server thread/WARN]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:247)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
[18:23:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:23:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[18:23:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[18:23:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[18:23:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[18:23:05] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[18:23:05] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[18:23:05] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909)
[18:23:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:23:05] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[18:23:05] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:23:05] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:23:05] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:23:05] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
[18:23:05] [Server thread/WARN]: 	... 16 more
[18:23:05] [Server thread/WARN]: Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.listener.protocollib.ProtocolLibService'
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
[18:23:05] [Server thread/WARN]: 	... 21 more
[18:23:05] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[18:23:05] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:23:05] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:23:05] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:23:05] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
[18:23:05] [Server thread/WARN]: 	... 38 more
[18:23:05] [Server thread/WARN]: Caused by: FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:57)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:38)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:259)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.concurrency.PacketTypeSet.addType(PacketTypeSet.java:35)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.addPacketHandler(ProtocolInjector.java:385)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:624)
[18:23:05] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:390)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.InventoryPacketAdapter.register(InventoryPacketAdapter.java:78)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.ProtocolLibService.setup(ProtocolLibService.java:70)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.ProtocolLibService.reload(ProtocolLibService.java:133)
[18:23:05] [Server thread/WARN]: 	at fr.xephi.authme.listener.protocollib.ProtocolLibService.<init>(ProtocolLibService.java:44)
[18:23:05] [Server thread/WARN]: 	... 43 more
[18:23:05] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[18:23:05] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[18:23:05] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown initiated...
[18:23:05] [Server thread/WARN]: [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown completed.
[18:23:05] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT-b2454 disabled!
```

**Comment by Maks1116** [comment]
I also noticed, that plugin crashes only in 1.16.x servers

**Comment by sgdc3** [comment]
You need to update ProtocolLib on your servers

**Comment by Maks1116** [comment]
I have latest dev build of protocollib

**Comment by TheCiROMG** [comment]
Still Persist, 1.20.1/1.21.1, with protocollib and latest last build Protocollib and Authme
