### ISSUE TITLE
[AuthME] idk what isn`t working. The Server just closes itself.

### ISSUE THREAD

**Issue by QuintusAimes** [AuthMe/AuthMeReloaded#2426]
******************************         Login Passed... Welcome       ******************************

[20:16:04] ain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:16:05] ain/INFO]: Reloading ResourceManager: Default, bukkit
[20:16:07] [Worker-Main-12/INFO]: Loaded 7 recipes
[20:16:09] [Server thread/INFO]: Starting minecraft server version 1.17.1
[20:16:09] [Server thread/INFO]: Loading properties
[20:16:10] [Server thread/INFO]: This server is running CraftBukkit version 3246-Spigot-6c1c1b2-dc764e7 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[20:16:10] [Server thread/INFO]: Debug logging is disabled
[20:16:10] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:16:10] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:16:10] [Server thread/INFO]: Default game type: SURVIVAL
[20:16:10] [Server thread/INFO]: Generating keypair
[20:16:10] [Server thread/INFO]: Starting Minecraft server on 116.202.245.24:27518
[20:16:10] [Server thread/INFO]: Using epoll channel type
[20:16:12] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[20:16:17] [Server thread/WARN]: Legacy plugin AuthMe v5.4.0-b1877 does not specify an api-version.
[20:16:17] [Server thread/INFO]: [EconomyShopGUI] Loading EconomyShopGUI v3.8.1
[20:16:17] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.3.47
[20:16:21] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.2.6+4b2d1e7
[20:16:22] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@10f28e6d]
[20:16:22] [Server thread/INFO]: [HolographicDisplays] Loading HolographicDisplays v2.4.9
[20:16:22] [Server thread/INFO]: [Essentials] Loading Essentials v2.19.0
[20:16:22] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.19.0
[20:16:22] [Server thread/INFO]: [MyCommand] Loading MyCommand v5.7.1
[20:16:22] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.19.0
[20:16:22] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.4.0-b1877
[20:16:22] [Server thread/INFO]: [Factions] Loading Factions v1.6.9.5-2.9.4-RC
[20:16:22] [Server thread/INFO]: [PlayerWarps] Loading PlayerWarps v6.9.2
[20:16:22] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.47
[20:16:22] [Server thread/INFO]:         __    
[20:16:22] [Server thread/INFO]:   |    |__)   LuckPerms v5.3.47
[20:16:22] [Server thread/INFO]:   |___ |      Running on Bukkit - CraftBukkit
[20:16:22] [Server thread/INFO]: 
[20:16:22] [Server thread/INFO]: [LuckPerms] Loading configuration...
[20:16:23] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[20:16:24] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[20:16:24] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[20:16:24] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 2275ms)
[20:16:24] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.2.6+4b2d1e7
[20:16:24] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[20:16:25] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[20:16:25] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_17_R1_2 as the Bukkit adapter
[20:16:27] [Server thread/INFO]: [WorldEdit] ====================================================
[20:16:27] [Server thread/INFO]: [WorldEdit]  WorldEdit works better if you use Paper 
[20:16:27] [Server thread/INFO]: [WorldEdit]  as your server software. 
[20:16:27] [Server thread/INFO]: [WorldEdit]   
[20:16:27] [Server thread/INFO]: [WorldEdit]  Paper offers significant performance improvements,
[20:16:27] [Server thread/INFO]: [WorldEdit]  bug fixes, security enhancements and optional
[20:16:27] [Server thread/INFO]: [WorldEdit]  features for server owners to enhance their server.
[20:16:27] [Server thread/INFO]: [WorldEdit]   
[20:16:27] [Server thread/INFO]: [WorldEdit]  Paper includes Timings v2, which is significantly
[20:16:27] [Server thread/INFO]: [WorldEdit]  better at diagnosing lag problems over v1.
[20:16:27] [Server thread/INFO]: [WorldEdit]   
[20:16:27] [Server thread/INFO]: [WorldEdit]  All of your plugins should still work, and the
[20:16:27] [Server thread/INFO]: [WorldEdit]  Paper community will gladly help you fix any issues.
[20:16:27] [Server thread/INFO]: [WorldEdit]   
[20:16:27] [Server thread/INFO]: [WorldEdit]  Join the Paper Community @ https://papermc.io
[20:16:27] [Server thread/INFO]: [WorldEdit] ====================================================
[20:16:27] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[20:16:27] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[20:16:27] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[20:16:27] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[20:16:27] [Server thread/INFO]: Preparing level "world"
[20:16:27] [Server thread/INFO]: -------- World Settings For [world] --------
[20:16:27] [Server thread/INFO]: Mob Spawn Range: 6
[20:16:27] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Carrot Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Potato Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Vine Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Kelp Growth Modifier: 100%
[20:16:27] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[20:16:27] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:16:27] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:16:27] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[20:16:27] [Server thread/INFO]: Max TNT Explosions: 100
[20:16:27] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:16:27] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:16:27] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:16:27] [Server thread/INFO]: Item Despawn Rate: 6000
[20:16:27] [Server thread/INFO]: Item Merge Radius: 2.5
[20:16:27] [Server thread/INFO]: View Distance: 5
[20:16:27] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[20:16:27] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:16:27] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:16:28] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[20:16:28] [Server thread/INFO]: Mob Spawn Range: 6
[20:16:28] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Carrot Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Potato Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Vine Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Kelp Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[20:16:28] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:16:28] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:16:28] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[20:16:28] [Server thread/INFO]: Max TNT Explosions: 100
[20:16:28] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:16:28] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:16:28] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:16:28] [Server thread/INFO]: Item Despawn Rate: 6000
[20:16:28] [Server thread/INFO]: Item Merge Radius: 2.5
[20:16:28] [Server thread/INFO]: View Distance: 5
[20:16:28] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[20:16:28] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:16:28] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:16:28] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[20:16:28] [Server thread/INFO]: Mob Spawn Range: 6
[20:16:28] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Carrot Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Potato Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Vine Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Kelp Growth Modifier: 100%
[20:16:28] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[20:16:28] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:16:28] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[20:16:28] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[20:16:28] [Server thread/INFO]: Max TNT Explosions: 100
[20:16:28] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:16:28] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:16:28] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:16:28] [Server thread/INFO]: Item Despawn Rate: 6000
[20:16:28] [Server thread/INFO]: Item Merge Radius: 2.5
[20:16:28] [Server thread/INFO]: View Distance: 5
[20:16:28] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[20:16:28] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:16:28] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:16:28] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:16:28] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[20:16:28] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[20:16:29] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[20:16:31] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[20:16:31] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[20:16:31] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[20:16:31] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[20:16:31] [Worker-Main-8/INFO]: Preparing spawn area: 4%
[20:16:32] [Worker-Main-9/INFO]: Preparing spawn area: 42%
[20:16:32] [Worker-Main-12/INFO]: Preparing spawn area: 68%
[20:16:33] [Worker-Main-13/INFO]: Preparing spawn area: 72%
[20:16:33] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[20:16:34] [Worker-Main-10/INFO]: Preparing spawn area: 86%
[20:16:34] [Worker-Main-10/INFO]: Preparing spawn area: 93%
[20:16:35] [Server thread/INFO]: Time elapsed: 6900 ms
[20:16:35] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[20:16:35] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[20:16:35] [Worker-Main-9/INFO]: Preparing spawn area: 2%
[20:16:36] [Worker-Main-11/INFO]: Preparing spawn area: 56%
[20:16:36] [Worker-Main-8/INFO]: Preparing spawn area: 85%
[20:16:37] [Worker-Main-8/INFO]: Preparing spawn area: 94%
[20:16:37] [Server thread/INFO]: Time elapsed: 2182 ms
[20:16:37] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[20:16:37] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[20:16:37] [Worker-Main-10/INFO]: Preparing spawn area: 70%
[20:16:37] [Server thread/INFO]: Time elapsed: 621 ms
[20:16:37] [Server thread/INFO]: [EconomyShopGUI] Enabling EconomyShopGUI v3.8.1
[20:16:38] [Server thread/INFO]: [EconomyShopGUI] Using lang-en.yml as language file.
[20:16:38] [Server thread/INFO]: [EconomyShopGUI] Shops.yml has been found!
[20:16:38] [Server thread/INFO]: [EconomyShopGUI] Sections.yml has been found!
[20:16:38] [Server thread/WARN]: [EconomyShopGUI] [ERROR] Disabled due to no Vault dependency found, please install Vault.
[20:16:38] [Server thread/WARN]: [EconomyShopGUI] [ERROR] Disabling the plugin...
[20:16:38] [Server thread/INFO]: [EconomyShopGUI] Disabling EconomyShopGUI v3.8.1
[20:16:38] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.4.9
[20:16:38] [Server thread/INFO]: [Essentials] Enabling Essentials v2.19.0
[20:16:38] [Server thread/INFO]: [Essentials] You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
[20:16:38] [Server thread/INFO]: Attempting to convert old kits in config.yml to new kits.yml
[20:16:38] [Server thread/INFO]: No kits found to migrate.
[20:16:38] [Server thread/INFO]: [Essentials] Starting Essentials ban format conversion
[20:16:38] [Server thread/INFO]: [Essentials] Starting usermap repair
[20:16:38] [Server thread/WARN]: [Essentials] Missing userdata folder, aborting
[20:16:38] [Server thread/INFO]: Attempting to migrate ignore list to UUIDs
[20:16:38] [Server thread/INFO]: Attempting to migrate legacy userdata keys to Configurate
[20:16:38] [Server thread/INFO]: Loaded 36837 items from items.json.
[20:16:38] [Server thread/INFO]: Using locale en_US
[20:16:38] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[20:16:38] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[20:16:38] [Server thread/WARN]: [Essentials] Detected supported permissions plugin LuckPerms without Vault installed.
[20:16:38] [Server thread/WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
[20:16:38] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[20:16:38] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.19.0
[20:16:38] [Server thread/INFO]: [EssentialsSpawn] Starting Metrics. Opt-out using the global bStats config.
[20:16:38] [Server thread/INFO]: [MyCommand] Enabling MyCommand v5.7.1
[20:16:38] [Server thread/INFO]: *-=-=-=-=-=-=-=-=-* MyCommand v.5.7.1*-=-=-=-=-=-=-=-=-=-*
[20:16:38] [Server thread/INFO]: | Vault plugin not found. Using BukkitPermissions
[20:16:38] [Server thread/INFO]: | No Economy support without Vault!
[20:16:38] [Server thread/INFO]: | Command file(s) found : 1
[20:16:38] [Server thread/INFO]: | Config : Ready.
[20:16:38] [Server thread/INFO]: | ProtocolLib not found.
[20:16:38] [Server thread/INFO]: | PlaceholderAPI: Not Found
[20:16:38] [Server thread/INFO]: | Custom commands loaded : 44
[20:16:38] [Server thread/INFO]: | You're running the latest version of MyCommand.
[20:16:38] [Server thread/INFO]: |          by emmerrei a.k.a. ivanfromitaly.           
[20:16:38] [Server thread/INFO]: *-=-=-=-=-=-=-=-=-=-*   Done!   *-=-=-=-=-=-=-=-=-=-=-*
[20:16:38] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.19.0
[20:16:38] [Server thread/INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[20:16:38] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.4.0-b1877
[20:16:38] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[20:16:38] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@1ba6e5f7
[20:16:38] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[20:16:38] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[20:16:38] [Server thread/INFO]: [AuthMe] AuthMe 5.4.0-b1877 disabled!
[20:16:38] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-2.9.4-RC
[20:16:38] [Server thread/INFO]: FAILED: You are missing dependencies!
[20:16:38] [Server thread/INFO]: FAILED: Please verify [Vault] is installed!
[20:16:38] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-2.9.4-RC (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.massivecraft.factions.zcore.util.Persist.save(Object)" because "com.massivecraft.factions.FactionsPlugin.getInstance().persist" is null
	at com.massivecraft.factions.Conf.save(Conf.java:613) ~[?:?]
	at com.massivecraft.factions.FactionsPlugin.onEnable(FactionsPlugin.java:134) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:514) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:428) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[20:16:38] [Server thread/INFO]: [PlayerWarps] Enabling PlayerWarps v6.9.2
[20:16:38] [Server thread/INFO]: [PlayerWarps] Cannot find vault, disabling...
[20:16:38] [Server thread/INFO]: [PlayerWarps] Disabling PlayerWarps v6.9.2
[20:16:38] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:16:39] [Server thread/INFO]: Done (12.192s)! For help, type "help"
[20:16:39] [Server thread/INFO]: Starting GS4 status listener
[20:16:39] [Server thread/INFO]: Thread Query Listener started
[20:16:39] [Query Listener #1/INFO]: Query running on 116.202.245.24:27518
[20:16:39] [Server thread/INFO]: Stopping server
[20:16:39] [Server thread/INFO]: [Factions] Disabling Factions v1.6.9.5-2.9.4-RC
[20:16:39] [Server thread/INFO]: [SaberFactions] ===== Shutdown Start =====
[20:16:39] [Server thread/ERROR]: Error occurred while disabling Factions v1.6.9.5-2.9.4-RC (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.massivecraft.factions.zcore.util.Persist.saveSync(Object)" because "com.massivecraft.factions.FactionsPlugin.instance.persist" is null
	at com.massivecraft.factions.Conf.saveSync(Conf.java:617) ~[?:?]
	at com.massivecraft.factions.zcore.util.ShutdownParameter.initShutdown(ShutdownParameter.java:19) ~[?:?]
	at com.massivecraft.factions.FactionsPlugin.onDisable(FactionsPlugin.java:331) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:448) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:917) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:733) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1094) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3246-Spigot-6c1c1b2-dc764e7]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[20:16:39] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat v2.19.0
[20:16:39] [Server thread/INFO]: [MyCommand] Disabling MyCommand v5.7.1
[20:16:39] [Server thread/INFO]: *-=-=-=-=-=-=-=-=-* MyCommand v.5.7.1*-=-=-=-=-=-=-=-=-=-*
[20:16:39] [Server thread/INFO]: | Tasks : Stopped all tasks.
[20:16:39] [Server thread/INFO]: *-=-=-=-=-=-=-=-=-=-*    Bye!   *-=-=-=-=-=-=-=-=-=-=-*
[20:16:39] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.19.0
[20:16:39] [Server thread/INFO]: [Essentials] Disabling Essentials v2.19.0
[20:16:39] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.9
[20:16:39] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.2.6+4b2d1e7
[20:16:39] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[20:16:39] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.3.47
[20:16:39] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[20:16:39] [Server thread/INFO]: [LuckPerms] Closing storage...
[20:16:39] [Server thread/INFO]: [LuckPerms] Goodbye!
[20:16:39] [Server thread/INFO]: Saving players
[20:16:39] [Server thread/INFO]: Saving worlds
[20:16:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20:16:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[20:16:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end

**Comment by krusic22** [comment]
> Legacy plugin AuthMe v5.4.0-b1877 does not specify an api-version.

**Comment by QuintusAimes** [comment]
> > Legacy plugin AuthMe v5.4.0-b1877 does not specify an api-version.

what does that mean ?

**Comment by QuintusAimes** [comment]
what should i do in that case dawnload a newer versikon of authme ?

**Comment by krusic22** [comment]
Yes.

**Comment by QuintusAimes** [comment]
okeay thanks !
