### ISSUE TITLE
MySQL Not working on pterodactyl

### ISSUE THREAD

**Issue by dabucz** [AuthMe/AuthMeReloaded#2509]
### What behaviour is observed?

```
[17:21:13 INFO]: [AuthMe] Enabling AuthMe v5.4.0-b1877
[17:21:15 INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
[17:21:15 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[17:21:17 WARN]: [Server thread] ERROR fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Exception during pool initialization.
[17:21:17 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 375 milliseconds ago.  The last packet sent successfully to the server was 372 milliseconds ago.
[17:21:17 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:21:17 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:21:17 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:21:17 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[17:21:17 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[17:21:17 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[17:21:17 WARN]:        at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:105)
[17:21:17 WARN]:        at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4580)
[17:21:17 WARN]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1342)
[17:21:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
[17:21:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
[17:21:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
[17:21:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[17:21:17 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[17:21:17 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:21:17 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:21:17 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:21:17 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[17:21:17 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[17:21:17 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[17:21:17 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:445)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:116)
[17:21:17 WARN]:        at fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:97)
[17:21:17 WARN]:        at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:157)
[17:21:17 WARN]:        at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:164)
[17:21:17 WARN]:        at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:69)
[17:21:17 WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:72)
[17:21:17 WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
[17:21:17 WARN]:        at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:26)
[17:21:17 WARN]:        at fr.xephi.authme.libs.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141)
[17:21:17 WARN]:        at fr.xephi.authme.libs.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181)
[17:21:17 WARN]:        at fr.xephi.authme.libs.jalu.injector.InjectorImpl.get(InjectorImpl.java:155)
[17:21:17 WARN]:        at fr.xephi.authme.libs.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56)
[17:21:17 WARN]:        at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:246)
[17:21:17 WARN]:        at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
[17:21:17 WARN]:        at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:136)
[17:21:17 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:21:17 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:21:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:21:17 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[17:21:17 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[17:21:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[17:21:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[17:21:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[17:21:17 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[17:21:17 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[17:21:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:21:17 WARN]: Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
[17:21:17 WARN]:        at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
[17:21:17 WARN]:        at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
[17:21:17 WARN]:        at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220)
[17:21:17 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:428)
[17:21:17 WARN]:        at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:90)
[17:21:17 WARN]:        ... 46 more
[17:21:17 WARN]: [AuthMe] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 375 milliseconds ago.  The last packet sent successfully to the server was 372 milliseconds ago.
[17:21:17 WARN]: [AuthMe] Please check your database settings in the config.yml file!
[17:21:17 WARN]: [AuthMe] Could not create data source: [CommunicationsException]: Communications link failure

The last packet successfully received from the server was 375 milliseconds ago.  The last packet sent successfully to the server was 372 milliseconds ago.
[17:21:17 WARN]: [AuthMe] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[17:21:17 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[17:21:17 INFO]: [AuthMe] Waiting for 0 tasks to finish
[17:21:17 INFO]: [AuthMe] AuthMe 5.4.0-b1877 disabled!
[17:21:17 INFO]: [UTitleAuth] Enabling UTitleAuth v3.0
[17:21:17 INFO]: [UTitleAuth] -----------------------------------
[17:21:17 INFO]: [ERROR] Plugin AuthMe Hooked not found!
[17:21:17 INFO]: [UTitleAuth] Disabling UTitleAuth v3.0
[17:21:17 INFO]: [UTitleAuth] -----------------------------------
[17:21:17 INFO]: [UTitleAuth] 
[17:21:17 INFO]: [UTitleAuth] Successfully Plugin Disable!
[17:21:17 INFO]: [UTitleAuth] Creator: BrunoAvixdub
[17:21:17 INFO]: [UTitleAuth] Thanks for use my plugin :D
[17:21:17 INFO]: [UTitleAuth] 
[17:21:17 INFO]: [UTitleAuth] -----------------------------------
[17:21:17 INFO]: [UTitleAuth] Plugin PlaceholderAPI Hooked Successfully!
[17:21:17 ERROR]: Error occurred while enabling UTitleAuth v3.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:100) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at com.github.undeadlydev.UTitleAuth.Runneable.RunUtils.<init>(RunUtils.java:18) ~[?:?]
        at com.github.undeadlydev.UTitleAuth.Main.onEnable(Main.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[17:21:17 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:21:17 INFO]: Done (11.109s)! For help, type "help" or "?"
container@pterodactyl~ Server marked as running...
[17:21:17 INFO]: Stopping server
[17:21:17 INFO]: [ProtocolLib] Disabling ProtocolLib v4.7.0
[17:21:17 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.1
[17:21:17 INFO]: [KeepTheWeather] Disabling KeepTheWeather v1.0
[17:21:17 INFO]: KeepTheWeather disabled!
[17:21:17 INFO]: [StaxSpawn] Disabling StaxSpawn v1.0
[17:21:17 INFO]: [StaxSpawn] Plugin se uspesne vypl delal stax
[17:21:17 INFO]: Saving players
[17:21:17 INFO]: Saving worlds
[17:21:17 INFO]: Saving chunks for level 'world'/Overworld
[17:21:17 INFO]: Saving chunks for level 'world_nether'/Nether
[17:21:17 INFO]: Saving chunks for level 'world_the_end'/The End
```

### Expected behaviour

.

### To Reproduce

.

### Plugin list

.

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

AuthMe-5.4.0

### Error log (if applicable)

.

### Configuration

.

**Comment by sgdc3** [comment]
Invalid, unsupported AuthMe version, no config provided.
