### ISSUE TITLE
Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by AsrielFBI** [AuthMe/AuthMeReloaded#2558]
### What behaviour is observed?

I have a nice mysql database and have done the configuration propperly to the authme config to connect to the db. But whent trying to load the server, it enters a loophole of restarting as authme states:

> Server thread/WARN
> 1:43:30
> 
> at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
> at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
> at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
> at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
> at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
> at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
> at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
> at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
> at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
> at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
> at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:172)
> at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:180)
> at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:77)
> at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
> at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
> ... 19 more
**Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed**

And cant do anything as it doesnt let me allow public key retrieval nor do something to prevent it!

### Expected behaviour

The expected behaviour should be:
 A) Just connecting without any problem, 
 B) Have an option to enable public key Retrieval as all database managers do have when configuring connection options!

### To Reproduce

Setup a simple docker database:
![imagen](https://user-images.githubusercontent.com/56162938/173208539-ba57e520-5051-4ec3-80e1-7fa5cd909ca0.png)

### Plugin list

Done on a testing server with no plugins!

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

Tested with: 5.6.0-beta2 and 5.6.0-SNAPSHOT

### Error log (if applicable)

https://paste.gg/p/anonymous/3750e17739cc4104b3b7a9fd1d01b2b2

### Configuration

https://paste.gg/p/anonymous/dcda48cf1cdf413fb538629facc98934

**Comment by AsrielFBI** [comment]
Found root cause of the problem: MySQL

Yes, it says you can use mysql db, but what they mean is to use MariaDB, mariadb worked perfectly fine.
