### ISSUE TITLE
Problem connecting to the server, only works locally

### ISSUE THREAD

**Issue by TheFiery** [AuthMe/AuthMeReloaded#2817]
### What behaviour is observed?

With AuthMe, I can only log in locally. If I do this while I'm connected to the server via my public ip, I can't log in.

I have investigated this problem, but no solution solved the problem.
I don't host MYSQL 

When I join locally it works very well 192.168.1.20
but I get this error in the console

```
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@238ed46f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@5af683a1 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@1df9bfa (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@4cd25f0a (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@192ac753 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@77afa45c (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@a52e118 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:47:33 ERROR] [STDERR]: [Server thread] WARN fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection fr.xephi.authme.libs.com.mysql.cj.jdbc.ConnectionImpl@5426d557 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

```
![2024-04-26_12 05 13](https://github.com/AuthMe/AuthMeReloaded/assets/78815430/ebb46644-b908-47fd-bade-1831398fa9a6)

then when I connect via my public ip, I can't log in even though I've entered the right password. 
![2024-04-26_12 05 37](https://github.com/AuthMe/AuthMeReloaded/assets/78815430/69fda709-9909-4d09-b7f1-21e5587e578b)

and in the console
```
[13:46:25 WARN] [AuthMe]: Plugin AuthMe v5.6.0-SNAPSHOT-b2623 generated an exception while executing task 20
java.lang.IllegalArgumentException: name cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23108!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayerExact(CraftServerMixin.java:601) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at fr.xephi.authme.service.BukkitService.getPlayerExact(BukkitService.java:191) ~[?:?]
        at fr.xephi.authme.process.login.AsynchronousLogin.displayOtherAccounts(AsynchronousLogin.java:335) ~[?:?]
        at fr.xephi.authme.process.login.AsynchronousLogin.performLogin(AsynchronousLogin.java:291) ~[?:?]
        at fr.xephi.authme.process.login.AsynchronousLogin.login(AsynchronousLogin.java:105) ~[?:?]
        at fr.xephi.authme.process.Management.lambda$performLogin$0(Management.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

I tested with an earlier version but same problem 
AuthMe 5.6.0-beta2 build n.2453

### Expected behaviour

I expect to be able to reach my server via my public ip 

### To Reproduce

1. configure config.yml
2. launch the server
3. connect using its public ip

### Plugin list

AuthMe
PlaceholderAPI
ProtocolLib

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

AuthMeReloaded v5.6.0-SNAPSHOT (build: 2623)

### Error log (if applicable)

https://paste.gg/da8a9163ff8e4f12a2bb34f3e321b3a2

### Configuration

https://paste.gg/5c2331d4b7cb4ff1901ee68a299cf5b1

**Comment by sgdc3** [comment]
@TheFiery please try again with the latest dev build: https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/
