### ISSUE TITLE
[13:01:29 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!

### ISSUE THREAD

**Issue by YingLuoNou** [AuthMe/AuthMeReloaded#2887]
### What behaviour is observed?

When I install authme I cannot start my server because it displays: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!

My server is paper-1.20-17

> [13:01:28 INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[13:01:29 WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[13:01:29 WARN]: ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[13:01:29 WARN]:        at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
[13:01:29 WARN]:        at ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
[13:01:29 WARN]:        at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:247)
[13:01:29 WARN]:        at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
[13:01:29 WARN]:        at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
[13:01:29 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[13:01:29 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[13:01:29 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:01:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:01:29 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562)
[13:01:29 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473)
[13:01:29 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[13:01:29 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[13:01:29 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[13:01:29 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[13:01:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:01:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[13:01:29 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[13:01:29 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
[13:01:29 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:01:29 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:01:29 WARN]:        at ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
[13:01:29 WARN]:        ... 19 more
[13:01:29 WARN]: Caused by: java.lang.NoClassDefFoundError: com/maxmind/db/NodeCache
[13:01:29 WARN]:        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
[13:01:29 WARN]:        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3572)
[13:01:29 WARN]:        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2737)
[13:01:29 WARN]:        at ch.jalu.injector.handlers.instantiation.StandardInjectionProvider.getInjectionConstructor(StandardInjectionProvider.java:61)
[13:01:29 WARN]:        at ch.jalu.injector.handlers.instantiation.StandardInjectionProvider.safeGet(StandardInjectionProvider.java:37)
[13:01:29 WARN]:        at ch.jalu.injector.handlers.instantiation.DefaultInjectionProvider.safeGet(DefaultInjectionProvider.java:32)
[13:01:29 WARN]:        at ch.jalu.injector.handlers.instantiation.DirectInstantiationProvider.resolve(DirectInstantiationProvider.java:19)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.findResolutionOrFail(InjectorImpl.java:227)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:153)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
[13:01:29 WARN]:        at ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
[13:01:29 WARN]:        at ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
[13:01:29 WARN]:        at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
[13:01:29 WARN]:        at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
[13:01:29 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:01:29 WARN]:        ... 22 more
[13:01:29 WARN]: Caused by: java.lang.ClassNotFoundException: com.maxmind.db.NodeCache
[13:01:29 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[13:01:29 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[13:01:29 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[13:01:29 WARN]:        ... 45 more
[13:01:29 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[13:01:29 INFO]: [AuthMe] Waiting for 0 tasks to finish
[13:01:29 INFO]: [AuthMe] AuthMe 5.7.0-SNAPSHOT-b2636 disabled!
[13:01:29 INFO]: Running delayed init tasks
[13:01:29 INFO]: Done (2.967s)! For help, type "help"
[13:01:29 INFO]: Stopping server
[13:01:29 INFO]: Saving players
[13:01:29 WARN]: [AuthMe] Error during SQL operation: [SQLException]: database connection closed

### Expected behaviour

It can work well

### To Reproduce

just start paper-1.20-17.jar

### Plugin list

just authme-5.7.0-SNAPSHOT

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

5.7.0

### Error log (if applicable)

https://gist.github.com/YingLuoNou/e3a12da084ad71515059463e9d4c2b4e

### Configuration

https://gist.github.com/YingLuoNou/de69e1706a8f64915c3d18028657245c.js

**Comment by krusic22** [comment]
Can you try updating your Paper jar to at least 1.21 - build 130?
