### ISSUE TITLE
Error with MythicMobs plugin

### ISSUE THREAD

**Issue by danieliustt** [AuthMe/AuthMeReloaded#2901]
### What behaviour is observed?

[08:57:31] [Server thread/ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerTeleportEvent
[08:57:31] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.api.skills.SkillCaster.getEntity()" because "caster" is null
[08:57:31] [Server thread/WARN]: 	at MythicMobs-5.8.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.listeners.triggers.DamageTriggerListeners.onTeleportTrigger(DamageTriggerListeners.java:657)
[08:57:31] [Server thread/WARN]: 	at MythicMobs-5.8.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[08:57:31] [Server thread/WARN]: 	at MythicMobs-5.8.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[08:57:31] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[08:57:31] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:57:31] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[08:57:31] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[08:57:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.teleport(PlayerConnection.java:1705)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.teleport(PlayerConnection.java:1674)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1670)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.a(PlayerList.java:319)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:134)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1472)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1449)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1372)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1350)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1239)
[08:57:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[08:57:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Expected behaviour

[08:57:31] [Server thread/ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerTeleportEvent

### To Reproduce

[08:57:31] [Server thread/ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerTeleportEvent

### Plugin list

[08:57:31] [Server thread/ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerTeleportEvent

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

Latest Dev Build

### Configuration

https://paste.gg/

**Comment by danieliustt** [comment]
# Should not logged in players be teleported to the spawn?
        # After the authentication they will be teleported back to
        # their normal position.
        teleportUnAuthedToSpawn: false


When true, then errors comes.

**Comment by danieliustt** [comment]
[10:04:51] [Server thread/ERROR]: [MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.player.PlayerTeleportEvent
[10:04:51] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.api.skills.SkillCaster.getEntity()" because "caster" is null
[10:04:51] [Server thread/WARN]: 	at MythicMobs-5.8.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.listeners.triggers.DamageTriggerListeners.onTeleportTrigger(DamageTriggerListeners.java:657)
[10:04:51] [Server thread/WARN]: 	at MythicMobs-5.8.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[10:04:51] [Server thread/WARN]: 	at MythicMobs-5.8.0-SNAPSHOT.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[10:04:51] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:04:51] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[10:04:51] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1468)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1367)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:229)
[10:04:51] [Server thread/WARN]: 	at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.service.TeleportationService.lambda$performTeleportation$0(TeleportationService.java:188)
[10:04:51] [Server thread/WARN]: 	at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.service.BukkitService.scheduleSyncTaskFromOptionallyAsyncTask(BukkitService.java:81)
[10:04:51] [Server thread/WARN]: 	at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.service.TeleportationService.performTeleportation(TeleportationService.java:185)
[10:04:51] [Server thread/WARN]: 	at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.service.TeleportationService.teleportNewPlayerToFirstSpawn(TeleportationService.java:117)
[10:04:51] [Server thread/WARN]: 	at authme-5.7.0-SNAPSHOT.jar//fr.xephi.authme.listener.PlayerListener.onPlayerJoin(PlayerListener.java:191)
[10:04:51] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor748.execute(Unknown Source)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[10:04:51] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:04:51] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[10:04:51] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[10:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:350)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1584)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1561)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1554)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1505)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1515)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1351)
[10:04:51] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341)
[10:04:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
