### ISSUE TITLE
AuthMe Crashing Server

### ISSUE THREAD

**Issue by astr1al** [AuthMe/AuthMeReloaded#662]
Hello again, I think this is an AuthMe issue, not 100% positive, but maybe the dev will recognize something there. 

Running AuthMe build #943
 [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-5a40365-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

Server log snippets http://pastebin.com/r3jukf4h

Crash Log http://pastebin.com/0QrjvChj

I apologize if the crash isn't related to AuthMe but wanted to at least share the other errors.

Thanks for taking a look!

**Comment by sgdc3** [comment]
@astr1al Hello, could you post your plugin list please? Thanks ;)

**Comment by sgdc3** [comment]
``` JAVA
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.server.v1_9_R1.EntityTracker.untrackEntity(EntityTracker.java:157)
    at net.minecraft.server.v1_9_R1.WorldManager.b(WorldManager.java:26)
    at net.minecraft.server.v1_9_R1.World.c(World.java:1023)
    at net.minecraft.server.v1_9_R1.WorldServer.c(WorldServer.java:1135)
    at net.minecraft.server.v1_9_R1.World.kill(World.java:1059)
    at net.minecraft.server.v1_9_R1.PlayerList.disconnect(PlayerList.java:408)
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1060)
    at net.minecraft.server.v1_9_R1.PlayerConnection.disconnect(PlayerConnection.java:244)
    at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.disconnect(AbstractListenerPlayIn.java:50)
    at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:218)
    at fr.xephi.authme.command.executable.authme.RegisterAdminCommand$1.run(RegisterAdminCommand.java:60)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```

**Comment by sgdc3** [comment]
```
 Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
```

```
    at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.disconnect(AbstractListenerPlayIn.java:50)
```

```
    at fr.xephi.authme.command.executable.authme.RegisterAdminCommand$1.run(RegisterAdminCommand.java:60)
```

**Comment by sgdc3** [comment]
@ljacqu What do you think about that? :/

**Comment by ljacqu** [comment]
I wrote a comment in here, which apparently has been deleted. Problem is 
RegisterAdminCommand$1.run(RegisterAdminCommand.java:60) -> uses `Player.kick()`, but the entire code block is run asynchronously. We cannot kick player asynchronously.

**Comment by sgdc3** [comment]
And how can we move the kick outside of the async context without breaking the right order of the checks?

**Comment by ljacqu** [comment]
Probably only possible with `BukkitScheduler#runTask` instead of the async methods :/

**Comment by astr1al** [comment]
@sgdc3 here's a pretty large plugin list. http://pastebin.com/mjrCpMHd

**Comment by astr1al** [comment]
I do have a skript running that executes a console command /authme register %player% %{_passwordvariable}%

because there is another issue where a player has to 
/register <password> <password> twice to register themselves otherwise.

**Comment by sgdc3** [comment]
are you sure this issue is still present? :/

**Comment by astr1al** [comment]
Yes, tested it out last night.

**Comment by sgdc3** [comment]
> I do have a skript running that executes a console command /authme register %player% %{_passwordvariable}%
> 
> because there is another issue where a player has to 
> /register twice to register themselves otherwise.

I mean this issue

**Comment by astr1al** [comment]
Sorry the /register issue was due to a skript I was running.

**Comment by ljacqu** [comment]
@astr1al Is there anything that is still open for this issue? Anything on our side that was causing problems?

**Comment by Xephi** [comment]
Tell me if that fixed the problem ?

https://github.com/AuthMe-Team/AuthMeReloaded/commit/e97b4641a1780c2cadd1101d4f24f42c9cac5a8c

**Comment by astr1al** [comment]
I think this was due to something on my end. this can be closed.

**Comment by astr1al** [comment]
Issue reopened. Experienced a crash again last night. Please see crash log in first post for stack trace.

**Comment by ljacqu** [comment]
Sorry for letting this idle. @astr1al Since you experienced the crash, has it ever happened again? Otherwise voting to close & to open a new issue should this happens again in the future.

**Comment by astr1al** [comment]
@ljacq @Xephi 
Apologies for taking so long to respond to this issue, it was not easy to reproduce and it would always happen at the worst moment. Since it nearly causes the machine to hang  I was never really patient enough and able to get you any useful information on this...Until now. :) Hopefully you are able to find something useful out of this.

[thread dump.txt](https://github.com/Xephi/AuthMeReloaded/files/865862/thread.dump.txt)

[CPU Profiler Snapshot](https://drive.google.com/drive/folders/0B4gbLqv0tkrNOXQyd0p3SjdHRnc?usp=sharing)

[Heap Dump](https://drive.google.com/file/d/0B4gbLqv0tkrNMW5teWlKUnhIQWs/view?usp=sharing)

[Plugins](http://pastebin.com/AJiEDKci)

This happend using AuthMe v5.2-SNAPSHOT-b1494
[15:15:41] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-72c2605-709783c (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)[m
[15:15:41] [Server thread/INFO]: Checking version, please wait...[m
[15:15:42] [Thread-79/INFO]: You are 196 version(s) behind[m

Thanks for taking a look.

**Comment by sgdc3** [comment]
@astr1al Could you try the latest dev builds? ;)

**Comment by astr1al** [comment]
Just dropped it in. I'll let you know if this pops up again. It could take a while since this only seems to happen maybe once or twice a month.

**Comment by sgdc3** [comment]
ok
